/**
 * Every user-facing string of the organiser screens lives here, so wording can change without touching components.
 * House words (a test enforces them): "Rider label" (never the old technical word), "Lycra" (never the old word for it),
 * "score" (never the old word for a judge's number), "Impression / Variety score".
 * Anything the code needs at run time (numbers, names) is a small function.
 */

import type { LabelMap } from "@/lib/schema-form/nodes";

const plural = (n: number, one: string, many: string) => (n === 1 ? one : many);

export interface Help {
  text: string;
  example?: string;
}

export const copy = {
  common: {
    save: "Save",
    saving: "Saving…",
    remove: "Remove",
    cancel: "Cancel",
    close: "Close",
    open: "Open",
    up: "↑",
    down: "↓",
    notSet: "Not set",
    choose: "Choose…",
    none: "None yet.",
    addPrefix: "+ Add",
    helpButton: "?",
    helpLabel: (what: string) => `Help: ${what}`,
    example: "Example:",
    toastDone: (title: string) => `✔ ${title}`,
    problem: (text: string) => `✖ ${text}`,
    fixedSuffix: "(fixed)",
    needsAttention: "✖ needs attention",
    unknownOption: (v: string) => `${v} (unknown)`,
    unsaved: "● Unsaved changes",
    imageTypes: "PNG, JPEG or WebP, up to 2 MB.",
  },

  join: {
    title: "Join as an official",
    intro: "Judges, spotters, head judge and announcer: enter the event code and the PIN from your card. Or scan your QR code.",
    eventIntro: (qr: boolean) => `Officials: enter your 6-digit PIN${qr ? ", or wait a moment while your QR code signs you in" : ""}.`,
    joinEvent: "Join the event",
    qrJoining: "Joining with your QR code…",
    eventCode: "Event code",
    pin: "Your 6-digit PIN",
    joining: "Joining…",
    button: "Join",
    iphoneTip: "iPhone tip: tap Share → “Add to Home Screen” first, then open the app from your home screen and join there. The home-screen app keeps its own login.",
    errors: {
      INVALID_PIN: "That event code or PIN is not recognised. Check the card you were given and try again.",
      INVALID_TOKEN: "This QR code has already been used or has expired. Ask the organiser for a new card, or type your PIN instead.",
      RATE_LIMITED: "Too many wrong tries. Wait ten minutes, or ask the organiser for help.",
      SEAT_LOCKED: "This seat is locked to another phone. Ask the organiser to unlock it.",
      NO_SESSION: "Your phone could not start a session. Check your connection and try again.",
      ORGANISER_SESSION: "This browser is signed in as an organiser. Use another browser or a private window to join as a judge or spotter.",
    } as Record<string, string>,
    otherError: "Something went wrong. Please try again.",
  },

  login: {
    title: "Organiser sign in",
    linkFailed: "That sign-in link did not work. It may have expired, or it was opened in a different browser than the one you asked from. Ask for a new one below.",
    email: "Your email address",
    send: "Email me a sign-in link",
    sending: "Sending…",
    notRegistered: "That email address is not registered as an organiser. Ask the owner to add you.",
    tooMany: "Too many sign-in emails were requested. Wait a few minutes (up to an hour) and try again.",
    couldNotSend: "The sign-in email could not be sent. Check the address and your connection, then try again.",
    sentTo: (to: string) => `✔ Link sent to ${to}.`,
    sameBrowserBefore: "Open the email on ",
    sameBrowserBold: "this same phone or computer, in this same browser",
    sameBrowserAfter: ", and tap the link. It works once.",
  },

  seat: {
    title: "Your seat",
    roles: { judge: "Judge", head: "Head judge", spotter: "Spotter", announcer: "Announcer" } as Record<string, string>,
    connected: "✔ Connected",
    switchedOff: "✖ This seat has been switched off by the organiser.",
    later: "The scorecard and spotter screens arrive in Phase 5. This phone stays connected to your seat, so you will not need to join again.",
    notConnected: "Not connected",
    noSeat: "This phone does not hold a seat yet.",
    joinLink: "Join with a PIN",
  },

  layout: {
    events: "Events",
    settings: "Organisation settings",
    signOut: "Sign out",
    organisation: "Organisation",
    navLabel: "Organiser",
  },

  landing: {
    tagline: "Live scoring for kitesurfing Big Air competitions.",
    join: "Officials: join with a PIN",
    organiser: "Organiser sign in",
    eventsHeading: "Events",
    none: "No events are published yet.",
    loadError: "The event list could not be loaded just now. Try again in a minute.",
    live: " · ● LIVE now",
    finished: " · finished",
  },

  orgHome: {
    noOrg: "You are not a member of any organisation yet. Ask the product owner to add you.",
    heading: (org: string) => `${org}: events`,
    newEvent: "+ New event",
    noDate: "No date yet",
    openSetup: "Open setup",
    empty: "No events yet. Press “New event” to start.",
    line: (date: string, status: string, slug: string) => `${date} · status: ${status} · /${slug}`,
  },

  orgSettings: {
    heading: "Organisation settings",
    readOnly: "Only owners and admins can change these settings. You can look, but not save.",
    name: "Organisation name",
    slug: "Web address (slug)",
    slugHint: "Lowercase letters, numbers and hyphens, for example “arrow”.",
    slugWarnTitle: "⚠ Changing the web address changes your public links.",
    slugWarn: (old: string) => `Anything that already points to “${old}” (printed QR codes, shared links) will stop working. Only continue if you have not shared links yet.`,
    understand: "I understand, change the address",
    logo: "Organisation logo",
    timeZone: "Default time zone for new events",
    timeZoneHint: "New events start with this time zone; each event can still choose its own.",
    save: "Save settings",
    saved: "Organisation settings saved",
    fixThese: "Some settings need fixing.",
    noMembership: "You are not a member of an organisation.",
    notAllowed: "Only owners and admins can change organisation settings.",
    slugTaken: "That web address is already used by another organisation.",
    slugTakenField: "Already taken: choose another",
    saveFailed: "The settings could not be saved. Nothing was changed; try again.",
    saveDenied: "The settings could not be saved (no permission). Nothing was changed.",
    validation: {
      slugMax: "The web address can be at most 40 characters",
      nameMin: "Give the organisation a name",
      nameMax: "That name is too long (80 characters at most)",
    },
  },

  logo: {
    choose: "Choose image",
    replace: "Replace image",
    uploading: "Uploading…",
    none: "No image",
    current: (label: string) => `${label} (current)`,
    chooseAria: (label: string) => `${label}: choose an image file`,
    wrongType: "That file is not a PNG, JPEG or WebP image. Save the logo as one of those and try again.",
    tooBig: (mb: string) => `That image is ${mb} MB. The limit is 2 MB: export a smaller version and try again.`,
    empty: "That file is empty.",
    uploadFailed: "The image could not be uploaded. Check your connection and try again.",
  },

  wizard: {
    railLabel: "Event setup steps",
    status: (s: string) => `Status: ${s}`,
    stepPicker: "Setup step",
    coming: " (coming soon)",
    attention: " (needs attention)",
    done: " (done)",
    soon: "soon",
    missingIn: (step: string) => `What is missing in ${step}`,
    steps: { event: "1. Event", divisions: "2. Divisions", riders: "3. Riders", officials: "4. Officials", draw: "5. Draw", schedule: "6. Run order & timetable" },
    missing: {
      name: "Give the event a name.",
      dates: "Set the first and last day of the event.",
      location: "Add the location.",
      noDivisions: "Add at least one division (for example Pro Men).",
      scoring: (d: string) => `${d}: choose how it is scored.`,
      format: (d: string) => `${d}: choose its format.`,
    },
  },

  event: {
    newHeading: (org: string) => `New event for ${org}`,
    newIntro: "Step 1 of the setup: the basics. You can add divisions, riders and officials after saving.",
    stepHeading: "Step 1: Event",
    formLabel: "Event details",
    basics: "Basics",
    name: "Event name",
    slug: "Web address (slug)",
    location: "Location",
    locationPlaceholder: "El Gouna, Egypt",
    firstDay: "First day",
    lastDay: "Last day",
    timeZone: "Time zone",
    timeZoneHint: "All times are shown in this zone.",
    slugPublishedTitle: "⚠ This event is published. Changing the address breaks links and QR codes that are already out.",
    understand: "I understand, change the address",
    branding: "Branding",
    eventLogo: "Event logo",
    sponsors: "Sponsor logos",
    noSponsors: "No sponsors yet.",
    sponsorName: (n: number) => `Sponsor ${n} name`,
    sponsorUrl: (n: number) => `Sponsor ${n} website (optional)`,
    sponsorLogo: (n: number) => `Sponsor ${n} logo`,
    sponsorUp: (n: number) => `Move sponsor ${n} up`,
    sponsorDown: (n: number) => `Move sponsor ${n} down`,
    sponsorRemove: "Remove sponsor",
    addSponsor: "+ Add sponsor",
    visibilityHeading: "What riders and spectators see",
    visibilityIntro: "Nothing is shown to riders or spectators until the head judge publishes it. Optionally:",
    showLive: "Show live scores during a heat (the head judge can switch this on per heat)",
    showResults: "Show results automatically when a heat is published",
    holdFinal: "Hold the final’s result until the organiser releases it (podium)",
    timing: "Timing and officials",
    readyCall: "Ready call (minutes before a heat)",
    livePoll: "Live update every (seconds)",
    grace: "Judges may still score after a heat (seconds)",
    judgesLog: "Judges may log attempts too (not only spotters)",
    windBanner: "Show the wind-call banner on public pages and the big screen",
    registration: "Rider registration",
    registrationOpen: "Registration is open (riders can register from the event page)",
    registrationNote: "Registration is closed until you switch it on. It only works once the event is published.",
    registrationCloses: "Registration closes after (optional)",
    registrationClosesHint: "The whole of this day still counts, in the event’s time zone.",
    joinHeading: "Officials’ join details",
    joinText: (origin: string, code: string) => `Officials join at ${origin}/join with the event code ${code} and their own personal PIN (you create seats and PINs in the Officials step). There is no single PIN for the whole event: every official has their own.`,
    eventCode: "Event code:",
    visibility: "Visibility",
    published: "Published: the event is listed on the home page and its public pages work",
    draftNote: "While unpublished (draft) only your team can see the event.",
    otherStatus: (s: string) => `This event is ${s}; its visibility is now controlled by the heat controls.`,
    create: "Create event",
    saveEvent: "Save event",
    next: "Next: Divisions →",
    created: "Event created",
    saved: "Event saved",
    fixThese: "Some settings need fixing. They are highlighted below.",
    notFound: "That event was not found, or you do not have access to it.",
    noOrg: "You are not a member of an organisation.",
    saveDenied: "The event could not be saved (no permission). Nothing was changed.",
    slugTaken: "That web address is already used by another event.",
    slugTakenField: "Already taken: choose another",
    notAllowedValue: "One of the values is not allowed. Check the highlighted fields.",
    saveFailed: "The event could not be saved. Nothing was changed; try again.",
    validation: {
      nameMin: "Give the event a name",
      nameMax: "That name is too long (100 characters at most)",
      locationMax: "Location is too long",
      pickDate: "Pick a date",
      endBeforeStart: "The last day cannot be before the first day",
      closesAfterEnd: "Registration cannot close after the event has ended",
      slugMin: "The web address needs at least 2 characters",
      slugMax: "The web address can be at most 60 characters",
      slugChars: "Use only lowercase letters, numbers and hyphens, starting with a letter or number",
      sponsorName: "give the sponsor a name",
      sponsorUrl: "a full web address, starting with https://",
      sponsorsMax: "at most 20 sponsors",
      useDate: "use a date",
      timeZone: "Not a known time zone (for example Africa/Cairo)",
    },
  },

  ident: {
    heading: "Rider identification",
    intro: "How officials recognise a rider from the beach. Every screen shows the same rider label built from this scheme.",
    lycraQuestion: "Will riders wear coloured lycras?",
    lycraYes: "Yes: each rider (or each heat) has a lycra colour",
    lycraNo: "No or not sure: identify riders by name",
    lycraHint: "Without lycras, the spotter calls out the rider’s name. You can change this at any time.",
    preset: "Start from a preset",
    custom: "Custom (edited)",
    primary: "Big text on every rider label (primary)",
    fallback: "If the primary is missing on the day (fallback)",
    noFallback: "No fallback",
    callout: "The spotter calls out",
    lycras: "Lycras",
    bibs: "Bib / sail numbers",
    secondary: "Small details on the rider label (secondary)",
    kiteFields: "Kite details to record",
    palette: "Colour palette (in slot order; colours are always written out as text too)",
    colourName: (n: number) => `Name of colour ${n}`,
    colourPicker: (name: string) => `${name} colour`,
    colourUp: (name: string) => `Move ${name} up`,
    colourDown: (name: string) => `Move ${name} down`,
    colourRemove: (name: string) => `Remove ${name}`,
    addColour: "+ Add colour",
    newColour: (n: number) => `Colour ${n}`,
    allowOverride: "Allow a different scheme for individual divisions",
    preview: "Preview:",
    previewCallout: "Spotter calls out:",
    saveName: "Save this scheme as a preset",
    presetName: "Preset name",
    savePreset: "Save as preset",
    presetSaved: (n: string) => `Preset “${n}” saved`,
    nameTooShort: "Give the preset a name (at least 2 characters).",
    saveFailed: "The preset could not be saved. Try again.",
    callouts: { colour: "The colour (“Red”)", number: "The number (“14”)", kite: "The kite (“Blue Orbit”)", name: "The rider’s name (“Sam Sample”)" },
    lycraAssign: { per_heat_slot: "The lycra colour changes every heat (each slot has a colour)", fixed_per_rider: "One colour per rider for the whole event", none: "No lycras" },
    bibNumbering: { none: "No numbers", per_event: "Numbers are unique in the whole event", per_division: "Numbers are unique inside each division" },
    kite: { brand: "Brand", model: "Model", size: "Size", colours: "Colours" },
    identifiers: {
      name: "Rider’s name",
      nationality: "Nationality",
      sponsor: "Sponsor",
      vest_colour: "Lycra colour",
      bib_number: "Bib / sail number",
      kite: "Kite (brand, model, size, colours)",
      kite_size_colour: "Kite size + colourway",
      rashguard_colour: "Rash guard / wetsuit colour",
      helmet_colour: "Helmet colour",
      photo: "Rider photo",
    } as Record<string, string>,
    validation: {
      colourKey: "colour key must be lowercase letters, numbers or _",
      colourName: "give the colour a name (it is always shown as text too)",
      colourHex: "colour must look like #e11d48",
      schemeName: "give the scheme a name",
      paletteMin: "the palette needs at least one colour",
      keysUnique: (d: string) => `colour keys must be unique (duplicate: ${d})`,
      namesUnique: "two colours share a name; colours are called out by name, so each needs its own",
      fallbackDiffers: "the fallback must differ from the primary identifier",
      invalid: (detail: string) => `Invalid identification scheme:\n${detail}`,
    },
  },

  riderLabel: {
    fallback: "(fallback)",
    notSet: "NOT SET",
    lycra: "Lycra",
    rashguard: "Rash guard",
    helmet: "Helmet",
    photoOnFile: "Photo on file",
    kiteSize: (size: string) => `${size} m`,
  },

  divisions: {
    stepHeading: "Step 2: Divisions",
    intro: "A division is a group that ranks together (for example Pro Men). Each has its own scoring rules and format. Everything can be started from a preset and adjusted.",
    lockBanner: "Editable until the first heat of this division starts; after that, unlock with a reason (recorded).",
    none: "No divisions yet. Add the first one below (for example “Pro Men”).",
    nameOf: (n: number) => `Name of division ${n}`,
    moveUp: (d: string) => `Move ${d} up`,
    moveDown: (d: string) => `Move ${d} down`,
    duplicate: "Duplicate",
    delete: "Delete",
    confirmDelete: (d: string) => `Yes, delete ${d}`,
    hasHeatsTitle: "This division already has heats",
    hasHeats: "This division has heats, so it cannot be deleted.",
    editRules: "Edit scoring & format",
    summary: (scoring: string, format: string, locked: boolean) => `Scoring: ${scoring} · Format: ${format}${locked ? " · 🔒 locked" : ""}`,
    notChosen: "not chosen yet",
    tabsLabel: (d: string) => `${d} settings`,
    tabScoring: "Scoring",
    tabFormat: "Format",
    newName: "New division name",
    newPlaceholder: "Pro Men",
    add: "+ Add division",
    added: "Division added",
    renamed: "Division renamed",
    deleted: "Division deleted",
    duplicated: (n: string) => `Duplicated as “${n}”`,
    copySuffix: " (copy)",
    errors: {
      nameMin: "Give the division a name (at least 2 characters).",
      nameMax: "That name is too long (60 characters at most).",
      unknownEvent: "Unknown event.",
      notFound: "That division was not found.",
      failed: "That did not work. Nothing was changed; try again.",
      rulesLocked: "Scoring and format are locked because a heat of this division has started. Unlock them with a written reason first.",
      hasHeats: "This division already has heats, so it cannot be deleted.",
      reason: "Write a reason (at least 5 characters).",
      notAllowed: "You do not have permission to do that.",
      presetNotFound: "That preset was not found.",
      presetInvalid: "The chosen preset is not valid.",
      notValidTogether: "These settings are not valid together.",
      presetName: "Give the preset a name (2 to 80 characters).",
      presetNotValid: "The settings are not valid yet, so they cannot be saved as a preset.",
      onlyOwn: "Only your own presets can get new versions. Use “Save as new preset” for built-in ones.",
      presetSaveFailed: "The preset could not be saved. Nothing was changed; try again.",
      cannotImport: "This file cannot be imported.",
    },
  },

  rules: {
    scoringPreset: "Scoring preset",
    formatPreset: "Start from a format",
    myPresets: "My organisation’s presets",
    builtIn: "Built-in presets",
    customUnsaved: "Custom ladder (not saved yet)",
    showAll: "Show all settings",
    showAllHint: "Simple shows only what most events need. Show all settings adds every option, each with a “?” explanation.",
    chooseFirst: (what: string) => `Choose a ${what} to see and edit its settings.`,
    scoringWord: "scoring preset",
    formatWord: "format",
    lockedTitle: "🔒 Scoring and format are locked: a heat of this division has started.",
    lockedText: "Changing rules mid-event affects results already entered. To change them anyway, write down why. It is kept in the audit log.",
    reason: "Reason for unlocking",
    unlock: "Unlock scoring and format",
    unlocked: "Unlocked. Your reason was written to the audit log.",
    fixTitle: "✖ Some settings need fixing before they can be saved:",
    saveFor: (kind: "scoring" | "format", d: string) => `Save ${kind} for ${d}`,
    savedFor: (kind: "scoring" | "format", d: string) => `${kind === "scoring" ? "Scoring" : "Format"} saved for ${d}`,
    discard: "Discard changes",
    saveFirst: "Save it as a preset first, then it is used for this division.",
    newPresetLabel: "Save these settings as a new preset",
    presetPlaceholder: "Preset name",
    saveNewPreset: "Save as new preset",
    saveNewVersion: (n: string) => `Save as new version of “${n}”`,
    presetSavedUsing: (n: string, d: string) => `Preset “${n}” saved; ${d} now uses it`,
    versionSavedUsing: (n: string, v: number, d: string) => `Saved “${n}” as version ${v}; ${d} now uses it`,
    export: "Export as JSON",
    import: "Import a JSON file…",
    importAria: (kind: string) => `Import a ${kind} JSON file`,
    pasteShow: "Paste JSON instead",
    pasteHide: "Hide paste box",
    pasteLabel: "Paste the JSON here",
    pasteImport: "Import pasted JSON",
    importNote: "Imports are always saved as a new preset of your organisation. Nothing existing is overwritten.",
    imported: (n: string) => `Imported “${n}” as a new preset. Press “Save for this division” to use it.`,
    fixedRoundsNote: "This format has its own fixed rounds. Change them under Show all settings → Custom ladder (advanced), or pick one of the three ladder types above to replace them.",
  },

  scoringSimple: {
    counting: "Which tricks count?",
    countingOther: "This preset counts tricks in a different way. Change that under Show all settings.",
    n: "Best tricks that count (N)",
    attempts: "Attempts allowed per rider per heat (M)",
    noLimit: "No limit on attempts per rider",
    judges: "Number of judges",
    judgesHint: "The panel size the rules are designed for.",
    aggregate: "How the judges’ scores are combined",
    aggregateOptions: { mean: "Plain average of the judges’ scores", trimmed_mean: "Trimmed average (highest and lowest dropped)", median: "The middle score (median)" },
    impression: "Judges also give an Impression / Variety score for each rider",
    impressionName: "Name of the score",
    impressionLow: "Lowest",
    impressionHigh: "Highest",
    impressionStep: "Step",
    defaultImpressionLabel: "Variety",
    seatsNote: "Which seats judge which division is set in the Officials step (next release).",
  },

  panelSentence: {
    plain: (n: number) => `${n} ${plural(n, "judge", "judges")} — plain average`,
    trimmed: (n: number) => `${n} judges — highest and lowest score dropped, the rest averaged`,
    median: (n: number) => `${n} ${plural(n, "judge", "judges")} — the middle score (median) counts`,
    trimmedTooFew: (n: number, from: number) => `${n} ${plural(n, "judge", "judges")} — plain average (trimming only starts from ${from} judges, so it is not used here)`,
    trimmedMixed: (n: number, from: number) => `${n} judges — plain average; with ${from} or more judges the highest and lowest score are dropped and the rest averaged`,
    rule: (from: number) => `Trimming only applies from ${from} judges. With fewer judges the plain average is used automatically.`,
  },

  scoringSentence: {
    bestNOfM: (n: number, m: number) => `Best ${n} of ${m} attempts`,
    bestN: (n: number) => `Best ${n} ${plural(n, "trick", "tricks")}`,
    distinct: " (each trick name counts once)",
    single: "Single best trick",
    singleOfM: (m: number) => `Single best trick of ${m} attempts`,
    all: "All tricks count",
    allUpTo: (m: number) => `All tricks count (up to ${m} attempts)`,
    none: "Judges do not score individual tricks",
    perCategory: (n: number, groups: string, each: string) => `Best ${n} ${plural(n, "trick", "tricks")} per category in ${groups}${each}`,
    groupsBest: (k: number) => `the best ${k} categories`,
    groupsAll: "every category",
    eachOf: (parts: string, others: number) => ` (${parts}; others ${others})`,
    upTo: (cat: string, n: number) => `${cat} up to ${n}`,
    attemptsSuffix: (m: number) => `, ${m} attempts`,
    weighted: (w: string) => `, counted tricks weighted ${w}`,
    multiplied: (x: string) => `, tricks × ${x}`,
    impression: (label: string, lo: string, hi: string, weight: string) => ` + ${label} ${lo}–${hi}${weight ? ` × ${weight}` : ""}`,
    averaged: "averaged",
    median: "median",
    trimmed: "trimmed average",
    judges: (n: number, how: string) => `${n} ${plural(n, "judge", "judges")} ${how}`,
  },

  formatSimple: {
    typeHeading: "Ladder type",
    typeLegend: "How riders progress through the event",
    types: {
      knockout: {
        title: "Knockout",
        explain: "Top riders from each heat advance to the next round; the rest are out.",
        example: "Example: heats of 4, top 2 go through.",
      },
      second_chance: {
        title: "Knockout with a second chance",
        explain: "Heat winners advance directly; 2nd and 3rd get one more heat to qualify.",
        example: "Example: King of the Air Round 1 → Round 2.",
      },
      pools: {
        title: "Pools to a final",
        explain: "Everyone rides once; all heat scores are ranked together and the top N ride the final.",
        example: "Example: 23 riders in 3 pools, best 6 to the final.",
      },
    },
    custom: "Custom ladder (advanced)",
    customActive: "This format is a custom ladder. Edit its rounds under Show all settings → Custom ladder (advanced).",
    startCustom: "+ Start a custom ladder",
    startCustomHint: "Add rounds, heat sizes, heat lengths, breaks, where riders come from and where each place goes. Save it as a preset to use it.",
    ridersPerHeat: "Riders per heat (target)",
    ridersPerPool: "Riders per pool (target)",
    minRiders: "Minimum riders per heat",
    tags: { atLeastTwo: "Every rider gets at least 2 heats", canBeOut: "Riders can be out after 1 heat" },
    minHeats: (n: number) => `Minimum heats per rider: ${n}`,
    advancePerHeat: "How many advance per heat",
    finalSize: "Final size",
    finalists: "How many make the final",
    secondChanceFixed: "Heat winners go straight through; the other riders get one more heat (the second-chance round). This part is fixed for this ladder type.",
    heatLengths: "Heat length (minutes)",
    lengthEarly: "Early rounds",
    lengthSemi: "Semi-finals",
    lengthFinal: "Final",
    lengthR1: "Round 1",
    lengthRep: "Second-chance round",
    lengthKo: "1 v 1 rounds",
    lengthPool: "Pool heats",
    breakHeat: "Break after each heat (minutes)",
    breakRound: "Break after the round (minutes)",
    perRound: {
      heading: "Heat length per round",
      note: "Pre-filled from the heat lengths above. Change a row to give that round its own length; breaks stay the same for every round. The rounds listed are those of the preview below.",
      row: (short: string, name: string) => `${short} · ${name}`,
      rowLabel: (short: string) => `Heat length: ${short} (minutes)`,
      own: "own length",
      reset: "Use the single settings for every round",
    },
    breaksNote: "For these ladder types the breaks apply to every round. To set them round by round, use Custom ladder (advanced).",
    seeding: "How riders are seeded into the next round",
    seedingOptions: { by_original_seed: "By original seeding", by_place_then_score: "By their result in the previous round (recommended)", by_heat_score: "By heat score" },
    seedingHelp: "Decides who meets whom in the next round.",
    previewWith: "Preview with",
    riders: "riders",
    previewLabel: "Format preview",
    ridingTime: (min: number) => `About ${min} minutes of riding, not counting breaks.`,
    fixFirst: "Fix the highlighted settings to see the preview.",
    minAboveTarget: "the minimum riders per heat cannot be more than the target",
    warning: (w: string) => `⚠ ${w}`,
  },

  ladder: {
    label: "Ladder diagram",
    title: (rounds: number, heats: number) => `${rounds} ${plural(rounds, "round", "rounds")}, ${heats} ${plural(heats, "heat", "heats")}`,
    heatSizes: (heats: number, range: string, minutes: string) => `${heats} ${plural(heats, "heat", "heats")} · ${range} riders · ${minutes} min`,
    heatBox: (n: number) => `${n} ${plural(n, "rider", "riders")}`,
    advancesWithoutRiding: "Advances without riding",
    heatName: (round: string, index: number) => `${round} H${index}`,
    /** Where a rider in a later heat comes from: "1st H1" (previous round), "1st R2 H5" (another round), "1st of all heats" (pools). */
    slotFrom: (place: number, round: string | null, heat: number) => `${ordinal(place)}${round ? ` ${round}` : ""}${heat > 0 ? ` H${heat}` : " of all heats"}`,
    place: (from: number, to: number) => (from === to ? `${ordinal(from)}` : `${ordinal(from)}–${ordinal(to)}`),
    rest: "the rest",
    out: "out",
    finalPlacing: "final placing",
    bestOfAll: (n: number) => `best ${n} of all heats`,
    arrow: "→",
    cannotRun: (n: number, why: string) => `With ${n} ${plural(n, "rider", "riders")}: this format cannot run (${why})`,
    sentence: (n: number, parts: string, total: number) => `With ${n} ${plural(n, "rider", "riders")}: ${parts} (${total} ${plural(total, "heat", "heats")})`,
    partHeats: (short: string, heats: number, range: string, advancing: number) => `${short} ${heats} ${plural(heats, "heat", "heats")} of ${range}${advancing > 0 ? ` + ${advancing} advancing without riding` : ""}`,
    partAdvancing: (short: string, advancing: number) => `${short} ${advancing} advancing without riding`,
    arrowText: " → ",
  },

  presets: {
    exportName: "my-preset",
    notJson: (where: string, detail: string) => `This file is not valid JSON${where}. ${detail}`,
    where: (line: number, col: number) => ` (line ${line}, column ${col})`,
    tooLarge: (kb: number, noun: string) => `This file is larger than ${kb} KB, which is far more than a ${noun} needs. Is it the right file?`,
    notObject: (noun: string) => `A ${noun} file must contain one JSON object (starting with “{”).`,
    wrongKind: (other: string, noun: string) => `This looks like a ${other}, not a ${noun}. Import it in the matching place.`,
    kindNames: { scoring_model: "scoring model", format_template: "format" },
    theFile: "the file",
    imported: "Imported",
  },

  friendly: {
    enterNumber: "Enter a number",
    needed: "This is needed",
    sectionNeeded: "This section is needed",
    wholeNumber: "Enter a whole number",
    atLeast: (n: string) => `Must be at least ${n}`,
    atMost: (n: string) => `Must be at most ${n}`,
    pickOne: "Pick one of the options",
    numbersList: "Type numbers separated by commas, like 1, 0.75, 0.5",
    nothingMore: "Nothing more to set for this choice.",
    cannotEdit: (label: string) => `${label}: this setting cannot be edited here.`,
    addCategoriesFirst: "Add trick categories first; limits are set per category.",
    use: (label: string) => `Use: ${label}`,
    offLabel: (label: string, off: string) => `${label}: ${off}`,
    value: "Value",
    notUsed: "Not used",
  },
};

function ordinal(n: number): string {
  const s = ["th", "st", "nd", "rd"];
  const v = n % 100;
  return `${n}${s[(v - 20) % 10] || s[v] || s[0]}`;
}
export { ordinal };

/** "?" texts of the hand-built forms (the generated forms carry theirs in the label maps below). */
export const help: Record<string, Help> = {
  "event.name": { text: "The name people see on the home page and the event page.", example: "Arrow Big Air 2026" },
  "event.slug": { text: "The last part of the event’s web address. Lowercase letters, numbers and hyphens.", example: "arrow-big-air-2026 gives …/e/arrow-big-air-2026" },
  "event.location": { text: "Where the event takes place.", example: "El Gouna, Egypt" },
  "event.dates": { text: "First and last day of the event. Days between them are the days you can schedule heats on.", example: "2 Oct to 4 Oct" },
  "event.timeZone": { text: "All times are shown in this time zone, wherever the viewer is.", example: "Africa/Cairo" },
  "event.logo": { text: "Shown at the top of the event page and on results.", example: "The Arrow logo as a PNG" },
  "event.sponsors": { text: "Sponsor logos are shown in a strip on the public pages, in the order you list them.", example: "WOO, then a local partner" },
  "event.visibility": { text: "Publishing is always the head judge’s decision. These switches only allow more to be shown to the public.", example: "Tick “show live scores” for a beach event with a big screen." },
  "event.showLive": { text: "Spectators can follow scores during a heat. The head judge can still switch this on or off for a single heat.", example: "Off: spectators see a heat only after it is published." },
  "event.showResults": { text: "When the head judge publishes a heat, its result appears on the public site at once. If off, the head judge or you release each result.", example: "Off is useful when results are read out first." },
  "event.holdFinal": { text: "The final’s result stays hidden from the public until you release it, so the podium can be announced first.", example: "You press Release after the prize-giving." },
  "event.readyCall": { text: "How long before a heat riders are called to the ready area.", example: "10 minutes" },
  "event.livePoll": { text: "How often public pages ask for new scores. Lower is faster but uses more data.", example: "7 seconds" },
  "event.grace": { text: "After a heat ends, judges can still enter or fix scores for this long.", example: "180 seconds is three minutes" },
  "event.judgesLog": { text: "Normally only spotters log attempts. Tick this if judges should log them too.", example: "Useful with a small team and no spotter." },
  "event.windBanner": { text: "Show the current wind call at the top of public pages and the big screen.", example: "“Wind: light, heats on hold”" },
  "event.registrationOpen": { text: "Lets riders sign up from the event page. Off until you switch it on. It only works once the event is published.", example: "Open it two weeks before the event." },
  "event.registrationCloses": { text: "The last day riders can register. The whole day still counts.", example: "1 Oct for an event starting on 2 Oct" },
  "ident.lycraQuestion": { text: "With lycras, each rider or heat has a colour. Without them, riders are recognised and called out by name.", example: "No lycras: the spotter says “Sam Sample”." },
  "ident.preset": { text: "A ready-made way of recognising riders. You can change everything after picking one.", example: "Lycra colour per heat is the classic KOTA style." },
  "ident.primary": { text: "The big text on every rider label, and the first thing judges and spotters look for.", example: "RED, or 14, or the rider’s name" },
  "ident.fallback": { text: "Used when a rider has no primary identifier on the day.", example: "Rash guard colour when lycras run out" },
  "ident.callout": { text: "What the spotter says aloud for this rider.", example: "“Red”, “14” or “Sam Sample”" },
  "ident.lycras": { text: "Whether the lycra colour changes every heat or stays with the rider.", example: "Per heat: the rider in slot 1 wears red in every heat." },
  "ident.bibs": { text: "Whether bib or sail numbers are used, and how far a number is unique.", example: "Unique in each division" },
  "ident.secondary": { text: "Extra small details on the rider label. Tick what helps officials.", example: "Nationality and sponsor" },
  "ident.kiteFields": { text: "Which kite details you record for each rider.", example: "Brand and size" },
  "ident.palette": { text: "The colours of your lycras, in slot order. Every colour is always written as text as well.", example: "Red, Yellow, Blue" },
  "ident.allowOverride": { text: "Lets a single division use a different way of recognising riders.", example: "Youth division by name, Pro by lycra" },
  "ident.savePreset": { text: "Keeps this scheme so you can pick it again for another event.", example: "Arrow lycras" },
  "scoring.preset": { text: "The rules for scoring this division. Pick one, then adjust below. Your changes stay on this division.", example: "KOTA-style: best 3 tricks plus an Impression / Variety score" },
  "scoring.counting": { text: "How many of a rider’s tricks add up to the heat total.", example: "Best 3 tricks of 7 attempts" },
  "scoring.n": { text: "How many of the rider’s best scored tricks count.", example: "3 means the three best tricks are added up" },
  "scoring.attempts": { text: "The most attempts a rider may log in one heat. Extra attempts are refused.", example: "7 attempts" },
  "scoring.judges": { text: "How many judges score each trick.", example: "3 judges" },
  "scoring.aggregate": { text: "How the judges’ scores for one trick become one number.", example: "Plain average of 3 judges" },
  "scoring.impression": { text: "One extra score per rider for the whole heat, on top of the tricks.", example: "Variety 0–10" },
  "scoring.impressionName": { text: "What judges see this score called.", example: "Variety or Overall" },
  "scoring.impressionRange": { text: "The lowest and highest score, and the smallest step on the score pad.", example: "0 to 10 in steps of 0.5" },
  "format.type": { text: "Choose how riders move from round to round. The rounds are created for you from the number of riders.", example: "Knockout: heats of 4, top 2 go through." },
  "format.preset": { text: "Start from a ready-made format. Changing the ladder type below replaces its rounds.", example: "Single elimination — heats of 4, top 2 advance" },
  "format.heatSize": { text: "How many riders each heat should have. Some heats can be one rider bigger.", example: "4" },
  "format.minHeat": { text: "Minimum riders per heat — the system will never make a heat smaller than this; extra riders make some heats one bigger.", example: "3 riders minimum with a target of 4: 14 riders make heats of 3, 3, 4 and 4" },
  "format.advance": { text: "How many riders from each heat go on to the next round.", example: "2 of 4" },
  "format.finalSize": { text: "How many riders ride the final.", example: "4" },
  "format.finalists": { text: "After every pool has ridden, all heat scores are ranked together and this many riders go to the final.", example: "Best 6 of 23 riders" },
  "format.perRound": { text: "Gives a round its own heat length. Rows that you do not change keep the length from the single setting above. Breaks are not affected.", example: "Round 1: 10 minutes, Final: 15 minutes" },
  "format.length": { text: "How long each heat lasts, in minutes.", example: "12 minutes in the semi-finals" },
  "format.breakHeat": { text: "Time between two heats of the same round.", example: "3 minutes" },
  "format.breakRound": { text: "Extra time between rounds.", example: "5 minutes" },
  "format.preview": { text: "Shows the ladder this format would create for a number of riders, using the same rules as the real draw.", example: "With 14 riders: R1 4 heats of 3–4 → SF → F" },
  "format.seeding": { text: "Decides who meets whom in the next round.", example: "By their result in the previous round (recommended)" },
  "rules.showAll": { text: "Shows every setting, not only the common ones. Each has its own “?”.", example: "Turn on to change weights, tie-breakers or flag-out." },
};

/* ---------------------------------------------------------------------------------------------------------------------
 * Labels of the generated forms (Advanced level). One entry per schema field; a test fails when a field has no entry, no
 * help or no example. `values` names the options of a choice.
 * ------------------------------------------------------------------------------------------------------------------- */
export const SCORING_HIDDEN = ["id", "version", "basedOn"] as const;

export const SCORING_LABELS: LabelMap = {
  name: { label: "Name", help: "The name shown in the preset list.", example: "Arrow: best 3 + Variety" },
  description: { label: "Description", help: "A sentence for organisers choosing a preset.", example: "Best 3 tricks plus a Variety score" },

  trick: { label: "Trick scoring", help: "How a single trick is scored by each judge.", example: "Four criteria scored 0–10" },
  "trick.entry": {
    label: "What judges enter for each trick",
    help: "Criteria: several scores that are combined. One score: a single number. Nothing: judges do not score tricks.",
    example: "Height, extremity, technicality and execution",
    values: { criteria: "Several criteria (height, extremity, …)", single: "One score per trick", none: "Nothing (overall score only)" },
  },
  "trick.scale": { label: "Trick score scale", help: "The range of the trick score after the criteria are combined.", example: "0 to 10 in steps of 0.1" },
  "trick.scale.min": { label: "Lowest", help: "The lowest possible trick score.", example: "0" },
  "trick.scale.max": { label: "Highest", help: "The highest possible trick score.", example: "10" },
  "trick.scale.step": { label: "Step", help: "The smallest jump on the score pad.", example: "0.1, or 0.5 for a quicker pad" },
  "trick.criteria": { label: "Criteria", help: "What judges score for each trick. The order is the order on the score pad.", example: "Height, Extremity, Technicality, Execution" },
  "trick.criteria.*": { label: "Criterion", help: "One thing judges score on every trick.", example: "Height" },
  "trick.criteria.*.key": { label: "Short code", help: "Lowercase letters, numbers and _. Must be unique.", example: "height" },
  "trick.criteria.*.label": { label: "Name shown to judges", help: "What appears on the score pad.", example: "Height & amplitude" },
  "trick.criteria.*.help": { label: "Hint for judges", help: "One line shown behind the “?” button on the score pad.", example: "How high and far the rider travels" },
  "trick.criteria.*.scale": { label: "Scale", help: "The range this criterion is scored on.", example: "0 to 10" },
  "trick.criteria.*.scale.min": { label: "Lowest", help: "The lowest possible score for this criterion.", example: "0" },
  "trick.criteria.*.scale.max": { label: "Highest", help: "The highest possible score for this criterion.", example: "10" },
  "trick.criteria.*.scale.step": { label: "Step", help: "The smallest jump for this criterion.", example: "0.1" },
  "trick.criteria.*.weight": { label: "Weight", help: "How much this criterion counts when the scores are combined.", example: "2 counts twice as much as 1" },
  "trick.criteria.*.sensorFill": { label: "Filled by the height sensor", help: "Lets a height sensor fill this criterion instead of the judge.", example: "Height", values: { height: "Height" } },
  "trick.combine": {
    label: "How criteria are combined",
    help: "Weighted average keeps the trick score on its scale. Add them up needs the criteria maximums to add to the trick maximum.",
    example: "Four criteria out of 10, weighted average, gives a trick score out of 10",
    values: { weighted_mean: "Weighted average, scaled to the trick scale", sum: "Add them up (maximums must add up to the trick scale)" },
  },
  "trick.crash": { label: "A crashed attempt", help: "What a crash is worth.", example: "Not counted: it simply does not count", values: { not_counted: "Is not counted", zero: "Counts as 0" } },
  "trick.allowNoScore": { label: "Judges may score “Missed” (did not see it)", help: "A judge who did not see a trick can skip it. It is left out of that trick’s average and never blocks publishing.", example: "A judge looked away during a kiteloop" },

  panel: { label: "Judge panel", help: "How many judges there are and how their scores are combined.", example: "3 judges, plain average" },
  "panel.minJudges": { label: "Fewest judges", help: "The panel size the rules are designed for. The app warns below 3.", example: "3" },
  "panel.maxJudges": { label: "Most judges", help: "The largest panel that can score a heat.", example: "7" },
  "panel.aggregate": {
    label: "How the judges’ scores are combined",
    help: "Plain average uses everyone. Trimmed average drops the highest and lowest first (only with enough judges). Median takes the middle score.",
    example: "5 judges, trimmed: the highest and lowest are dropped, the other 3 averaged",
    values: { mean: "Plain average", trimmed_mean: "Trimmed average (drop highest and lowest)", median: "Median (middle score)" },
  },
  "panel.trimMinJudges": { label: "Trim only with at least this many judges", help: "Below this number the plain average is used automatically.", example: "5" },
  "panel.decimals": { label: "Decimal places for scores and totals", help: "How scores are rounded.", example: "2 shows 7.25" },
  "panel.outlierWarnPct": { label: "Warn the head judge when two judges differ by more than (% of the scale)", help: "A warning on the head judge screen, nothing is changed.", example: "15 means 1.5 points on a 0–10 scale" },
  "panel.requireAllJudges": { label: "Every judge must score before publishing", help: "The head judge can still override with a written reason.", example: "On: a heat cannot be published while a judge is missing" },

  heat: { label: "Counting and heat total", help: "Which tricks count and how the heat total is made.", example: "Best 3 tricks plus a Variety score" },
  "heat.counting": { label: "Which tricks count", help: "Choose the rule, then fill in its details.", example: "Best 3 tricks" },
  "heat.counting=best_n": { label: "Best N tricks" },
  "heat.counting=best_per_category": { label: "Best tricks per category" },
  "heat.counting=single_best": { label: "Single best trick" },
  "heat.counting=all": { label: "All tricks" },
  "heat.counting=none": { label: "No tricks (overall score only)" },
  "heat.counting.n": { label: "Number of tricks that count", help: "How many of the best tricks are added up.", example: "3" },
  "heat.counting.distinctTrickNames": { label: "Each trick name counts only once", help: "Only the best of identically named tricks counts.", example: "Two backrolls: only the better one counts" },
  "heat.counting.maxPerCategory": { label: "Tricks per category that count", help: "Applies to every category not listed in the next setting.", example: "1: only the best kiteloop counts" },
  "heat.counting.perCategoryMax": { label: "Different limit for some categories", off: "Same limit for every category", help: "Lets some categories count more tricks than the rest.", example: "kiteloop: 2 lets two kiteloops count while other categories keep the limit above" },
  "heat.counting.perCategoryMax.*": { label: "Tricks that count", help: "How many tricks of this category count.", example: "2" },
  "heat.counting.categoriesCounted": { label: "Number of categories that count", help: "Only the best categories count. Empty means every category.", example: "3" },
  "heat.counting.requireDistinctCategories": { label: "Counted tricks must come from different categories", help: "Stops one category from filling every counting place.", example: "On: three kiteloops cannot fill three places" },
  "heat.trickWeight": { label: "Multiplier on the counted tricks", help: "Multiplies the sum of the counted tricks. 1 means no change.", example: "2 doubles the trick total" },
  "heat.countedWeights": { label: "Weights for the counted tricks, best first", off: "All counted tricks count fully", help: "Each counted trick can count for more or less, best trick first. Missing entries count as 1. Tie-breaks always use the raw scores.", example: "1, 0.75, 0.5: the best counts fully, the second three quarters, the third half" },
  "heat.countedWeights.*": { label: "Weight", help: "The weight of one counted trick.", example: "0.75" },
  "heat.impression": { label: "Impression / Variety score", off: "No Impression / Variety score", help: "One extra score per rider for the whole heat, on top of the tricks.", example: "Variety 0–10" },
  "heat.impression.label": { label: "Name shown to judges", help: "What judges see this score called.", example: "Variety" },
  "heat.impression.help": { label: "Hint for judges", help: "One line shown behind the “?” button.", example: "Variety, risk, style and flow" },
  "heat.impression.scale": { label: "Scale", help: "The range of this score.", example: "0 to 10" },
  "heat.impression.scale.min": { label: "Lowest", help: "The lowest possible score.", example: "0" },
  "heat.impression.scale.max": { label: "Highest", help: "The highest possible score.", example: "10" },
  "heat.impression.scale.step": { label: "Step", help: "The smallest jump on the score pad.", example: "0.5" },
  "heat.impression.weight": { label: "Weight in the heat total", help: "How much this score counts in the total.", example: "1 adds it as it is" },
  "heat.impression.required": { label: "Publishing waits until every judge has scored every rider", help: "The head judge can still override with a written reason.", example: "On: a missing Variety score blocks publishing" },
  "heat.total": { label: "Heat total", help: "How the total is shown.", example: "Points and percent" },
  "heat.total.display": { label: "Show the total as", help: "Points are the plain total. Percent compares with the best possible total.", example: "Both: 31.54 (78.9%)", values: { raw: "Points", percent: "Percent", both: "Points and percent" } },
  "heat.total.maxRaw": { label: "Maximum possible total (for percent)", off: "Work it out automatically", help: "Used only for percent. Automatic works out the best possible total from the counting rule.", example: "40" },
  "heat.landedRatioHint": { label: "Show landed / attempted to judges before the Impression / Variety score", help: "A reminder of how many attempts a rider landed.", example: "5 landed of 7 attempts" },
  "heat.maxAttemptsPerRider": { label: "Attempts allowed per rider per heat", off: "No limit", help: "The most attempts a rider may log. Extra attempts are refused.", example: "7" },
  "heat.duplicateWindowSec": { label: "Flag possible duplicate attempts within (seconds)", help: "Two spotters logging the same rider within this time are flagged for the head judge.", example: "20" },

  categories: { label: "Trick categories", help: "Groups of tricks, used by the spotter and by “best per category”.", example: "Kiteloop, Board-off, Rotation" },
  "categories.*": { label: "Category", help: "One group of tricks.", example: "Kiteloop tricks" },
  "categories.*.key": { label: "Short code", help: "Lowercase letters, numbers and _.", example: "kiteloop" },
  "categories.*.label": { label: "Name", help: "What the spotter sees.", example: "Kiteloop tricks" },
  "categories.*.examples": { label: "Example tricks", help: "Tricks shown as suggestions to the spotter.", example: "Single loop, S-loop" },
  "categories.*.examples.*": { label: "Example", help: "One example trick.", example: "Double loop" },
  "categories.*.colour": { label: "Colour (hex, optional)", help: "A colour for this category on spotter screens.", example: "#e11d48" },

  tieBreakers: { label: "Tie-breakers, in order", help: "When totals are equal, the first tie-breaker that separates the riders decides. Highest and next counted trick use the raw scores.", example: "Highest counted trick, then Impression / Variety, then the head judge" },
  "tieBreakers.*": {
    label: "Tie-breaker",
    help: "One rule for separating riders with equal totals.",
    example: "Highest counted trick",
    values: {
      highest_counted_trick: "Highest counted trick",
      next_counted_trick: "Next counted trick",
      impression: "Impression / Variety score",
      most_landed: "Most tricks landed",
      highest_any_trick: "Highest trick of any kind",
      head_judge: "Head judge decides",
      share_place: "Share the place",
    },
  },

  modifiers: { label: "Penalties and rider status", help: "What happens after interference, or when a rider does not start, finish or is disqualified.", example: "Interference drops the best trick" },
  "modifiers.interference": { label: "Interference", help: "A rider interfering with another rider.", example: "Drop the best trick" },
  "modifiers.interference.penalty": { label: "Penalty", help: "What interference costs the rider.", example: "Drop the best trick", values: { drop_best_trick: "Drop the best trick", percent: "Percent of the total", points: "Fixed points", none: "No penalty" } },
  "modifiers.interference.value": { label: "Amount", help: "Percent or points, depending on the penalty.", example: "10 percent" },
  "modifiers.interference.allowMultiple": { label: "Each interference counts separately", help: "If off, a second interference costs nothing more.", example: "On: two interferences drop two tricks" },
  "modifiers.dns": { label: "Did not start (DNS)", help: "A rider who did not start.", example: "Placed last with no total" },
  "modifiers.dns.placing": { label: "Placing", help: "Where the rider is placed.", example: "Last", values: { last: "Last" } },
  "modifiers.dns.total": { label: "Total", help: "The total the rider gets.", example: "0" },
  "modifiers.dnf": { label: "Did not finish (DNF)", help: "A rider who stopped during the heat.", example: "Keeps the scores earned before stopping" },
  "modifiers.dnf.keepScores": { label: "Rider keeps the scores earned before stopping", help: "If off, a rider who stops loses all scores.", example: "On" },
  "modifiers.dsq": { label: "Disqualified (DSQ)", help: "A rider disqualified from the heat.", example: "Placed after the DNS riders" },
  "modifiers.dsq.placing": { label: "Placing", help: "Where the rider is placed.", example: "Last", values: { last: "Last" } },
  "modifiers.dsq.total": { label: "Total", help: "The total the rider gets.", example: "0" },

  heightSensor: { label: "Height sensor", help: "Uses jump heights measured by a sensor.", example: "Highest jump as a side award" },
  "heightSensor.enabled": { label: "Use a height sensor", help: "Turn on only when heights are measured.", example: "Off when judged by eye" },
  "heightSensor.source": { label: "Where heights come from", help: "Typed in by hand, or a live feed from the sensor.", example: "Typed in by hand", values: { manual: "Typed in by hand", woo_api: "WOO sensor feed" } },
  "heightSensor.use": { label: "How heights are used", help: "Only shown, used to fill the Height criterion, or worth bonus points.", example: "Fills the Height criterion", values: { display: "Only shown", height_criterion: "Fills the Height criterion", bonus: "Adds bonus points" } },
  "heightSensor.mapping": { label: "Metres to score", off: "Not used", help: "How a height in metres becomes a score.", example: "5 m is 0, 25 m is 10" },
  "heightSensor.mapping=linear": { label: "Straight line between two heights" },
  "heightSensor.mapping=bands": { label: "Height bands" },
  "heightSensor.mapping.fromM": { label: "From (metres)", help: "The height that scores the low end.", example: "5" },
  "heightSensor.mapping.toM": { label: "To (metres)", help: "The height that scores the high end.", example: "25" },
  "heightSensor.mapping.toScore": { label: "Score range", help: "The scores at the low and high height.", example: "0 to 10" },
  "heightSensor.mapping.toScore.0": { label: "Score at the low height", help: "The score at the lowest height.", example: "0" },
  "heightSensor.mapping.toScore.1": { label: "Score at the high height", help: "The score at the highest height.", example: "10" },
  "heightSensor.mapping.bands": { label: "Bands", help: "Each band gives a score from a minimum height upwards.", example: "From 10 m scores 5" },
  "heightSensor.mapping.bands.*": { label: "Band", help: "One height band.", example: "From 10 m: 5" },
  "heightSensor.mapping.bands.*.minM": { label: "From (metres)", help: "The minimum height of this band.", example: "10" },
  "heightSensor.mapping.bands.*.score": { label: "Score", help: "The score for this band.", example: "5" },
  "heightSensor.bonus": { label: "Bonus points", off: "Not used", help: "Extra points for jumping above a threshold.", example: "1 point per metre above 10 m, at most 5" },
  "heightSensor.bonus.perMetreAbove": { label: "Points per metre above the threshold", help: "Bonus for each metre above the threshold.", example: "1" },
  "heightSensor.bonus.thresholdM": { label: "Threshold (metres)", help: "Bonus starts above this height.", example: "10" },
  "heightSensor.bonus.capPoints": { label: "Most bonus points", help: "The bonus never exceeds this.", example: "5" },
  "heightSensor.award": { label: "Side award", help: "Extra prizes based on heights.", example: "Highest jump" },
  "heightSensor.award.highestJump": { label: "Rank riders by highest jump", help: "Keeps a list of the highest measured jumps for a side award.", example: "On for a highest-jump prize" },
};

export const FORMAT_HIDDEN = ["id", "basedOn", "kind"] as const;

const SEEDING_VALUES = { snake: "Snake (1 to A, 2 to B, …)", sequential: "In order", manual: "By hand", random: "Random draw" };
const UNEVEN_VALUES = {
  minimum_riders: "Target and minimum riders per heat",
  smaller_heats_for_top_seeds: "Smaller heats for the top seeds",
  one_larger_heat: "One larger heat",
  byes_top_seeds: "Top seeds advance without riding",
};
const RESEED_VALUES = { by_original_seed: "By original seeding", by_place_then_score: "By their result in the previous round (recommended)", by_heat_score: "By heat score" };
const RESEED = { label: "How riders are seeded into the next round", help: "Decides who meets whom in the next round.", example: "By their result in the previous round (recommended)", values: RESEED_VALUES };

export const FORMAT_LABELS: LabelMap = {
  name: { label: "Name", help: "The name shown in the format list.", example: "Arrow knockout" },
  description: { label: "Description", help: "A sentence for organisers choosing a format.", example: "Heats of 4, top 2 advance" },
  entrants: { label: "Field size this format suits", help: "The field sizes this template was designed for. The per-round values decide.", example: "6 to 36 riders" },
  "entrants.min": { label: "Fewest riders", help: "Below this the preview warns you.", example: "6" },
  "entrants.max": { label: "Most riders", off: "No upper limit", help: "Above this the preview warns you.", example: "36" },
  vestColours: { label: "Lycra colours, in slot order", help: "The colours given to the slots of a heat when lycras change every heat.", example: "Red, yellow, blue, green" },
  "vestColours.*": { label: "Colour", help: "One lycra colour.", example: "red" },
  timing: { label: "Default timing (minutes)", help: "Defaults used to pre-fill new rounds. The per-round values decide.", example: "10 minute heats" },
  "timing.defaultHeatMin": { label: "Heat length", help: "Used when a round has no heat length of its own.", example: "10" },
  "timing.defaultBreakAfterHeatMin": { label: "Break after each heat", help: "Minutes between two heats of the same round.", example: "3" },
  "timing.defaultBreakAfterRoundMin": { label: "Break after the round", help: "Extra minutes between rounds.", example: "5" },

  rounds: { label: "Custom ladder (advanced)", help: "Each round is dealt into heats. Later rounds take riders from earlier rounds.", example: "Round 1 (heats of 4), then a Final" },
  "rounds.*": { label: "Round", help: "One round of the ladder.", example: "Round 1" },
  "rounds.*.id": { label: "Short code", help: "Used by other rounds to refer to this one.", example: "R1, SF or F" },
  "rounds.*.name": { label: "Name", help: "The round’s full name.", example: "Semi-finals" },
  "rounds.*.shortName": { label: "Short name", help: "Used in tight spaces such as the timetable.", example: "SF" },
  "rounds.*.heatSize": { label: "Riders per heat (target)", help: "How many riders each heat of this round should have.", example: "4" },
  "rounds.*.minHeatSize": { label: "Minimum riders per heat", help: "Minimum riders per heat — the system will never make a heat smaller than this; extra riders make some heats one bigger. Used when the rule below is “Target and minimum riders per heat”.", example: "3" },
  "rounds.*.durationMin": { label: "Heat length (minutes)", help: "How long each heat of this round lasts. Empty uses the default timing.", example: "12" },
  "rounds.*.breakAfterHeatMin": { label: "Break after each heat (minutes)", help: "Minutes between two heats of this round. Empty uses the default timing.", example: "3" },
  "rounds.*.breakAfterRoundMin": { label: "Break after the round (minutes)", help: "Extra minutes after the last heat of this round. Empty uses the default timing.", example: "5" },
  "rounds.*.entrantsFrom": { label: "Where the riders come from", help: "The seed list, or places from earlier rounds.", example: "Places 1 and 2 of Round 1" },
  "rounds.*.entrantsFrom.*": { label: "Source", help: "One source of riders.", example: "Places from an earlier round" },
  "rounds.*.entrantsFrom.*=seeds": { label: "The seed list (all riders)" },
  "rounds.*.entrantsFrom.*=round_places": { label: "Places from an earlier round" },
  "rounds.*.entrantsFrom.*.round": { label: "Earlier round", help: "The round the riders come from.", example: "R1" },
  "rounds.*.entrantsFrom.*.places": { label: "Places that come through", help: "Comma separated finishing places.", example: "1, 2" },
  "rounds.*.entrantsFrom.*.places.*": { label: "Place", help: "One finishing place.", example: "1" },
  "rounds.*.seeding": { label: "How riders are dealt into heats", help: "How the riders of this round are spread over its heats.", example: "Snake: seeds 1 and 2 go to different heats", values: SEEDING_VALUES },
  "rounds.*.uneven": { label: "When the field does not divide evenly", help: "What to do when riders do not fill the heats evenly. Only custom ladders offer the older rules.", example: "Smaller heats for the top seeds", values: UNEVEN_VALUES },
  "rounds.*.heatCountOverride": { label: "Force this number of heats", help: "Overrides the number of heats worked out from the riders.", example: "1 puts everyone in one heat" },
  "rounds.*.reseed": RESEED,
  "rounds.*.advance": { label: "Where each place goes", help: "One rule per group of places: to a later round, out, or to the final placing.", example: "1st–2nd to the Final, the rest out" },
  "rounds.*.advance.*": { label: "Rule", help: "One rule for a group of places.", example: "Places 1, 2 go to F" },
  "rounds.*.advance.*.places": { label: "Places", off: "Everyone else", help: "Comma separated finishing places, or everyone else.", example: "1, 2" },
  "rounds.*.advance.*.places.*": { label: "Place", help: "One finishing place.", example: "1" },
  "rounds.*.advance.*.to": { label: "Goes to", help: "A later round, “eliminated” or “final_placing” (the ranking of the last heat).", example: "F" },
  "rounds.*.crossHeat": { label: "Rank riders across all heats (pools)", off: "Not used", help: "Ranks every rider of the round together, not heat by heat.", example: "Pools: best 6 of all riders go to the final" },
  "rounds.*.crossHeat.advanceTop": { label: "How many advance", help: "How many of the best riders go on.", example: "6" },
  "rounds.*.crossHeat.to": { label: "Advance to round", help: "The round they go to.", example: "F" },
  "rounds.*.crossHeat.combine": { label: "Combine heat scores by", help: "Best heat, or the sum of a rider’s heats.", example: "Best heat", values: { best: "Best heat", sum: "Sum of heats" } },
  "rounds.*.crossHeat.tieBreak": { label: "Tie-break", help: "How equal riders are separated.", example: "Scoring rules, then seed", values: { scoring_model_then_seed: "Scoring rules, then seed" } },
  "rounds.*.minRidersToRun": { label: "Fewest riders for a heat to run", help: "A heat with fewer riders is skipped.", example: "2" },

  generator: { label: "Ladder settings", help: "The ladder type and its numbers. The rounds are created from these.", example: "Knockout, heats of 4" },
  "generator=single_elimination": { label: "Knockout" },
  "generator=dingle_elimination": { label: "Knockout with a second chance" },
  "generator=pools_to_final": { label: "Pools to a final" },
  "generator.params": { label: "Numbers", help: "The numbers that shape the ladder.", example: "Riders per heat 4" },
  "generator.params.heatSize": { label: "Riders per heat (target)", help: "How many riders each heat should have. Some heats can be one rider bigger.", example: "4" },
  "generator.params.minHeatSize": { label: "Minimum riders per heat", help: "Minimum riders per heat — the system will never make a heat smaller than this; extra riders make some heats one bigger.", example: "3" },
  "generator.params.advancePerHeat": { label: "How many advance per heat", help: "How many riders from each heat go on.", example: "2" },
  "generator.params.finalSize": { label: "Final size", help: "How many riders ride the final.", example: "4" },
  "generator.params.earlyMin": { label: "Early rounds: heat length (minutes)", help: "How long heats last before the semi-finals.", example: "10" },
  "generator.params.semiMin": { label: "Semi-finals: heat length (minutes)", help: "How long semi-final heats last.", example: "12" },
  "generator.params.finalMin": { label: "Final: heat length (minutes)", help: "How long the final lasts.", example: "15" },
  "generator.params.seeding": { label: "How riders are dealt into heats", help: "How the first round is spread over its heats.", example: "Snake", values: SEEDING_VALUES },
  "generator.params.uneven": { label: "When the field does not divide evenly", help: "An older rule kept for saved formats. New formats use the target and the minimum riders per heat.", example: "Smaller heats for the top seeds", values: UNEVEN_VALUES },
  "generator.params.reseed": RESEED,
  "generator.params.r1HeatSize": { label: "Round 1: riders per heat (target)", help: "How many riders each first-round heat should have. Some heats can be one rider bigger.", example: "3" },
  "generator.params.r1Min": { label: "Round 1: heat length (minutes)", help: "How long first-round heats last.", example: "13" },
  "generator.params.repMin": { label: "Second-chance round: heat length (minutes)", help: "How long the extra heats for 2nd and 3rd last.", example: "10" },
  "generator.params.koMin": { label: "1 v 1 rounds: heat length (minutes)", help: "How long the 1 v 1 heats last.", example: "10" },
  "generator.params.finalists": { label: "How many make the final", help: "After every pool has ridden, all heat scores are ranked together and this many go to the final.", example: "6" },
  "generator.params.poolMin": { label: "Pool heat length (minutes)", help: "How long each pool heat lasts.", example: "12" },
  "generator.params.poolRounds": { label: "Pool rounds", help: "Whether everyone rides one or two pool rounds.", example: "One", values: { "1": "One", "2": "Two" } },
  "generator.params.poolCombine": { label: "Combine pool rounds by", help: "Best pool score, or the sum of both rounds.", example: "Best heat", values: { best: "Best heat", sum: "Sum of heats" } },
  "generator.params.crossPoolTieBreak": { label: "Tie-break between pools", help: "How equal riders from different pools are separated.", example: "Scoring rules, then seed", values: { scoring_model_then_seed: "Scoring rules, then seed" } },

  placings: { label: "Final placings", help: "How riders knocked out are placed.", example: "Shared places such as 13=" },
  "placings.eliminated": { label: "Riders knocked out share their place", help: "Shared: every rider knocked out in the same round shares a place. Ranked: they are ordered by their heat score.", example: "Shared: 13=", values: { shared: "Shared (e.g. 13=)", by_heat_score: "Ranked by heat score" } },
  "placings.finalHeatIsRanking": { label: "The final heat decides places 1 to N", help: "The ranking of the last heat gives the top places.", example: "Always on" },
  roundDurationMin: { label: "Heat length per round", off: "Same for every round", help: "Gives some rounds their own heat length. Rounds not listed keep the length from the ladder settings. Breaks are not affected.", example: "R1: 10, F: 15" },
  "roundDurationMin.*": { label: "Heat length (minutes)", help: "The heat length of this round.", example: "15" },
  flagOut: { label: "Flag-out", off: "No flag-out", help: "KOTA-style: in 3-rider heats the lowest-scoring rider is flagged out at minute X and the other two ride on. Off by default.", example: "Round 1, flag out one rider at minute 8" },
  "flagOut.rounds": { label: "Rounds with flag-out", help: "The rounds where a rider is flagged out.", example: "R1" },
  "flagOut.rounds.*": { label: "Round code", help: "One round code.", example: "R1" },
  "flagOut.atMin": { label: "At minute", help: "How many minutes into the heat the flag-out happens.", example: "8" },
  "flagOut.count": { label: "Riders flagged out", help: "How many riders leave the heat.", example: "1" },
};
