-- GENERATED by `npm run db:combine`. Do not edit. Paste into Supabase > SQL Editor > New query > Run.
-- Safe to run once on an empty project.

-- ===== migration 20260929100000_helpers.sql =====
-- Phase 3 / step 1: shared helpers. `private` is not exposed through the API (only `public` is).
create schema if not exists private;
grant usage on schema private to anon, authenticated, service_role;

create or replace function private.set_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;


-- ===== migration 20260929100100_tables.sql =====
-- Phase 3 / step 2: every table in docs/05 §5 (plus the approved additions, docs/05 §12).
-- Statuses are text + CHECK (easier to evolve than enums). Scores are numeric(5,2) / totals numeric(6,2).

-- ---------------------------------------------------------------- tenants and events
create table public.organisations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]*$'),
  branding jsonb not null default '{}',
  plan text not null default 'free',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.memberships (
  id uuid primary key default gen_random_uuid(),
  organisation_id uuid not null references public.organisations on delete cascade,
  user_id uuid not null references auth.users on delete cascade,
  role text not null default 'staff' check (role in ('owner', 'admin', 'staff')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organisation_id, user_id)
);

create table public.events (
  id uuid primary key default gen_random_uuid(),
  organisation_id uuid not null references public.organisations on delete cascade,
  name text not null,
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]*$'),
  location text,
  timezone text not null default 'Africa/Cairo',
  start_date date,
  end_date date,
  status text not null default 'draft' check (status in ('draft', 'published', 'live', 'complete')),
  settings jsonb not null default '{"publicLiveScores":"after_publish","readyCallMin":10,"judgeGraceSec":180,"judgesMayLogAttempts":false,"livePollSec":7}',
  branding jsonb not null default '{}',
  join_pin_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------- presets
create table public.scoring_models (
  id uuid primary key default gen_random_uuid(),
  organisation_id uuid references public.organisations on delete cascade, -- null = system preset
  key text not null,
  name text not null,
  version int not null default 1,
  json jsonb not null,
  content_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint scoring_models_key_unique unique nulls not distinct (organisation_id, key, version)
);

create table public.format_templates (
  id uuid primary key default gen_random_uuid(),
  organisation_id uuid references public.organisations on delete cascade,
  key text not null,
  name text not null,
  version int not null default 1,
  json jsonb not null,
  content_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint format_templates_key_unique unique nulls not distinct (organisation_id, key, version)
);

create table public.trick_vocabularies (
  id uuid primary key default gen_random_uuid(),
  organisation_id uuid references public.organisations on delete cascade,
  event_id uuid references public.events on delete cascade,
  key text not null,
  json jsonb not null,
  content_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trick_vocabularies_key_unique unique nulls not distinct (organisation_id, event_id, key)
);

-- ---------------------------------------------------------------- officials and panels
create table public.judge_seats (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events on delete cascade,
  name text not null,
  role text not null check (role in ('judge', 'head', 'spotter', 'announcer')),
  pin_hash text,                      -- hashed 6-digit PIN, shown once on the printable card
  qr_token_hash text,                 -- sha-256 of a single-use QR token
  qr_token_expires_at timestamptz,
  locked boolean not null default false, -- true: a PIN can no longer rebind this seat to another phone
  auth_user_id uuid references auth.users on delete set null,
  bound_at timestamptz,
  device_label text,
  active boolean not null default true,
  scores boolean not null default false, -- convenience flag; scoring rights come from panel_members
  spotter_assignment jsonb,
  status text not null default 'active' check (status in ('active', 'pending')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.panels (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.panel_members (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events on delete cascade, -- filled by trigger
  panel_id uuid not null references public.panels on delete cascade,
  judge_seat_id uuid not null references public.judge_seats on delete cascade,
  seat_no int not null check (seat_no > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (panel_id, judge_seat_id),
  unique (panel_id, seat_no)
);

-- ---------------------------------------------------------------- divisions, riders, entries
create table public.divisions (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events on delete cascade,
  name text not null,
  sort_order int not null default 0,
  scoring_model_id uuid references public.scoring_models,
  scoring_overrides jsonb not null default '{}', -- deep-merge object over the model, e.g. {"heat":{"maxAttemptsPerRider":5}}
  format_template_id uuid references public.format_templates,
  format_params jsonb not null default '{}',
  panel_id uuid references public.panels on delete set null,
  status text not null default 'draft' check (status in ('draft', 'ready', 'running', 'complete')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.riders (
  id uuid primary key default gen_random_uuid(),
  organisation_id uuid not null references public.organisations on delete cascade,
  first_name text not null,
  last_name text not null,
  nationality text,
  dob date,
  email text,
  phone text,
  sponsor text,
  woo_id text,
  photo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.entries (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events on delete cascade, -- filled by trigger
  division_id uuid not null references public.divisions on delete cascade,
  rider_id uuid not null references public.riders,
  seed int,
  status text not null default 'registered' check (status in ('registered', 'confirmed', 'withdrawn', 'no_show')),
  source text not null default 'manual' check (source in ('self', 'import', 'manual')),
  paid boolean not null default false,
  consent_at timestamptz,
  identifiers jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (division_id, rider_id)
);

-- ---------------------------------------------------------------- ladder
create table public.rounds (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events on delete cascade, -- filled by trigger
  division_id uuid not null references public.divisions on delete cascade,
  sort_order int not null default 0,
  name text not null,
  short_name text,
  spec jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.heats (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events on delete cascade,  -- filled from the round by trigger
  division_id uuid not null references public.divisions on delete cascade, -- filled from the round by trigger
  round_id uuid not null references public.rounds on delete cascade,
  number int not null,
  number_suffix text,                 -- e.g. "R" for a re-run
  status text not null default 'scheduled' check (status in ('scheduled', 'running', 'paused', 'ended', 'under_review', 'published', 'cancelled')),
  duration_sec int not null default 600 check (duration_sec > 0),
  started_at timestamptz,             -- server time; only the state-machine trigger sets these
  paused_at timestamptz,
  paused_total_sec int not null default 0,
  ended_at timestamptz,
  published_at timestamptz,
  flag_out jsonb,
  manual_override boolean not null default false,
  live_rev int not null default 0,    -- bumped by trigger on any attempt/score/impression/penalty/slot change
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.heat_slots (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events on delete cascade, -- filled by trigger
  heat_id uuid not null references public.heats on delete cascade,
  position int not null,
  entry_id uuid references public.entries on delete set null,
  vest_colour text,
  source jsonb,
  place int,
  total numeric(6,2),                 -- written by the server at publish only, never provisional values
  breakdown jsonb,
  modifier text check (modifier in ('DNS', 'DNF', 'DSQ')),
  flagged_out boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (heat_id, position)
);

-- ---------------------------------------------------------------- attempts and scores
create table public.trick_attempts (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events on delete cascade, -- filled by trigger
  heat_id uuid not null references public.heats on delete cascade,
  entry_id uuid not null references public.entries,
  seq int not null,
  client_key uuid not null unique,    -- idempotency key for retries from the phone queue
  direction text check (direction in ('left', 'right')),
  category_key text,
  trick_name text,
  trick_parts jsonb not null default '{}',
  status text not null check (status in ('landed', 'crashed')),
  height_m numeric(5,2),
  created_by_seat uuid references public.judge_seats on delete set null,
  input_method text not null default 'builder' check (input_method in ('builder', 'text', 'speech')),
  raw_text text,
  deleted_at timestamptz,
  deleted_by uuid,
  possible_duplicate_of uuid references public.trick_attempts on delete set null,
  video_ts numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (heat_id, entry_id, seq)
);

create table public.trick_scores (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events on delete cascade, -- filled by trigger
  heat_id uuid not null references public.heats on delete cascade,   -- filled by trigger
  attempt_id uuid not null references public.trick_attempts on delete cascade,
  judge_seat_id uuid not null references public.judge_seats,
  criteria jsonb not null default '{}',
  score numeric(5,2) check (score >= 0),
  missed boolean not null default false,
  flag text check (flag in ('crash', 'wrong_rider', 'duplicate', 'other')),
  client_key uuid not null unique,
  client_rev bigint not null default 0, -- newer edits win; late retries of older edits are ignored
  version int not null default 1,
  edited_by uuid,
  edit_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (attempt_id, judge_seat_id),
  check ((missed and score is null) or (not missed and score is not null))
);

create table public.impression_scores (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events on delete cascade, -- filled by trigger
  heat_id uuid not null references public.heats on delete cascade,
  entry_id uuid not null references public.entries,
  judge_seat_id uuid not null references public.judge_seats,
  value numeric(5,2) not null check (value >= 0),
  client_key uuid not null unique,
  client_rev bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (heat_id, entry_id, judge_seat_id)
);

create table public.penalties (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events on delete cascade, -- filled by trigger
  heat_id uuid not null references public.heats on delete cascade,
  entry_id uuid not null references public.entries,
  type text not null check (type in ('INT', 'other')),
  value jsonb not null default '{}',
  reason text,
  issued_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Append-only: no updated_at, triggers reject UPDATE and DELETE.
create table public.heat_results (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events on delete cascade, -- filled by trigger
  heat_id uuid not null references public.heats on delete cascade,
  entry_id uuid not null references public.entries,
  place int,
  total numeric(6,2),
  percent numeric(5,2),
  breakdown jsonb,
  published_at timestamptz not null default now(),
  version int not null default 1,
  created_at timestamptz not null default now(),
  unique (heat_id, entry_id, version)
);

-- ---------------------------------------------------------------- timetable and wind
create table public.schedule_plans (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events on delete cascade,
  day date not null,
  name text not null,
  items jsonb not null default '[]',
  anchors jsonb not null default '{}',
  actual_starts jsonb not null default '{}',
  hold jsonb,
  defaults jsonb not null default '{}',
  active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.wind_calls (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events on delete cascade,
  status text not null check (status in ('red', 'amber', 'green')),
  message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------- audit and join bookkeeping
-- Append-only. event_id has no foreign key on purpose: the trail outlives what it describes.
create table public.audit_log (
  id uuid primary key default gen_random_uuid(),
  event_id uuid,
  actor_user_id uuid,
  actor_seat_id uuid,
  action text not null,
  table_name text not null,
  row_id uuid,
  before jsonb,
  after jsonb,
  reason text,
  at timestamptz not null default now()
);

-- Service-only: failed/successful join attempts, for rate limiting.
create table public.join_attempts (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events on delete cascade,
  ip text not null,
  seat_id uuid,
  ok boolean not null,
  at timestamptz not null default now()
);


-- ===== migration 20260929100200_indexes_triggers.sql =====
-- Phase 3 / step 2b: indexes, updated_at triggers, server-filled columns, live counter, heat state machine, immutability.

-- ---------------------------------------------------------------- indexes (every foreign key, plus the hot paths)
create index on public.memberships (user_id);
create index on public.events (organisation_id);
create index on public.riders (organisation_id);
create index on public.scoring_models (organisation_id);
create index on public.format_templates (organisation_id);
create index on public.trick_vocabularies (organisation_id);
create index on public.trick_vocabularies (event_id);
create index on public.judge_seats (event_id);
create index on public.judge_seats (auth_user_id);
create unique index judge_seats_one_seat_per_login on public.judge_seats (event_id, auth_user_id) where auth_user_id is not null;
create index on public.panels (event_id);
create index on public.panel_members (event_id);
create index on public.panel_members (judge_seat_id);
create index on public.divisions (event_id);
create index on public.divisions (scoring_model_id);
create index on public.divisions (format_template_id);
create index on public.divisions (panel_id);
create index on public.entries (event_id);
create index on public.entries (rider_id);
create index on public.rounds (event_id);
create index on public.rounds (division_id);
create index on public.heats (event_id);
create index on public.heats (division_id);
create index on public.heats (round_id);
create unique index heats_number_unique on public.heats (division_id, number, coalesce(number_suffix, ''));
create index on public.heat_slots (event_id);
create index on public.heat_slots (entry_id);
create index on public.trick_attempts (event_id);
create index on public.trick_attempts (entry_id);
create index trick_attempts_live_count on public.trick_attempts (heat_id, entry_id) where deleted_at is null; -- the attempt-cap count
create index on public.trick_attempts (created_by_seat);
create index on public.trick_scores (event_id);
create index on public.trick_scores (heat_id);
create index on public.trick_scores (attempt_id);
create index on public.trick_scores (judge_seat_id);
create index on public.impression_scores (event_id);
create index on public.impression_scores (heat_id);
create index on public.impression_scores (entry_id);
create index on public.impression_scores (judge_seat_id);
create index on public.penalties (event_id);
create index on public.penalties (heat_id);
create index on public.penalties (entry_id);
create index on public.heat_results (event_id);
create index on public.heat_results (entry_id);
create index on public.schedule_plans (event_id);
create unique index schedule_plans_one_active on public.schedule_plans (event_id, day) where active;
create index on public.wind_calls (event_id, created_at desc);
create index on public.audit_log (event_id, at desc);
create index on public.audit_log (table_name, row_id);
create index on public.join_attempts (event_id, ip, at desc);

-- ---------------------------------------------------------------- updated_at
do $$
declare t text;
begin
  foreach t in array array[
    'organisations','memberships','events','scoring_models','format_templates','trick_vocabularies','judge_seats','panels','panel_members',
    'divisions','riders','entries','rounds','heats','heat_slots','trick_attempts','trick_scores','impression_scores','penalties',
    'schedule_plans','wind_calls'
  ] loop
    execute format('create trigger z_updated_at before update on public.%I for each row execute function private.set_updated_at()', t);
  end loop;
end $$;

-- ---------------------------------------------------------------- server-filled columns (never trusted from the client)
create or replace function private.fill_denorm() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  v_event uuid; v_div uuid; v_heat public.heats; v_att public.trick_attempts;
begin
  case tg_table_name
    when 'entries' then
      select d.event_id into v_event from public.divisions d where d.id = new.division_id;
      new.event_id := v_event;
    when 'rounds' then
      select d.event_id into v_event from public.divisions d where d.id = new.division_id;
      new.event_id := v_event;
    when 'panel_members' then
      select p.event_id into v_event from public.panels p where p.id = new.panel_id;
      new.event_id := v_event;
    when 'heats' then
      select r.event_id, r.division_id into v_event, v_div from public.rounds r where r.id = new.round_id;
      new.event_id := v_event;
      new.division_id := v_div;
    when 'trick_scores' then
      select * into v_att from public.trick_attempts a where a.id = new.attempt_id;
      new.event_id := v_att.event_id;
      new.heat_id := v_att.heat_id;
      v_event := v_att.event_id;
    else -- heat_slots, trick_attempts, impression_scores, penalties, heat_results
      select * into v_heat from public.heats h where h.id = new.heat_id;
      new.event_id := v_heat.event_id;
      v_event := v_heat.event_id;
      -- a rider can only be placed in, or log attempts for, a heat of their own division
      if tg_table_name in ('heat_slots', 'trick_attempts', 'impression_scores') and new.entry_id is not null then
        if not exists (select 1 from public.entries e where e.id = new.entry_id and e.division_id = v_heat.division_id) then
          raise exception 'ENTRY_NOT_IN_DIVISION';
        end if;
      end if;
  end case;
  if new.event_id is null then
    raise exception 'PARENT_NOT_FOUND';
  end if;
  return new;
end $$;

do $$
declare t text;
begin
  foreach t in array array['entries','rounds','panel_members','heats','heat_slots','trick_attempts','trick_scores','impression_scores','penalties','heat_results'] loop
    execute format('create trigger a_fill_denorm before insert on public.%I for each row execute function private.fill_denorm()', t);
  end loop;
end $$;
-- a heat can be re-parented only by the server; keep event/division in step with the round on update
create trigger a_fill_denorm_upd before update of round_id on public.heats for each row execute function private.fill_denorm();

-- ---------------------------------------------------------------- live counter (public pages poll on this)
create or replace function private.bump_live_rev() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  update public.heats set live_rev = live_rev + 1 where id = coalesce(new.heat_id, old.heat_id);
  return null;
end $$;

do $$
declare t text;
begin
  foreach t in array array['trick_attempts','trick_scores','impression_scores','penalties','heat_slots'] loop
    execute format('create trigger z_bump_live_rev after insert or update or delete on public.%I for each row execute function private.bump_live_rev()', t);
  end loop;
end $$;

-- ---------------------------------------------------------------- heat state machine: server time is truth
create or replace function private.heats_guard() returns trigger
language plpgsql as $$
declare
  priv boolean := current_user in ('service_role', 'postgres', 'supabase_admin');
  v_end timestamptz;
  v_started timestamptz := new.started_at; v_paused_at timestamptz := new.paused_at;
  v_paused_total int := new.paused_total_sec; v_ended timestamptz := new.ended_at; v_published timestamptz := new.published_at;
begin
  if not priv then
    -- server-owned columns cannot be edited by hand
    new.started_at := old.started_at; new.paused_at := old.paused_at; new.paused_total_sec := old.paused_total_sec;
    new.ended_at := old.ended_at; new.published_at := old.published_at; new.live_rev := old.live_rev;
    new.event_id := old.event_id; new.division_id := old.division_id; new.round_id := old.round_id;
    v_started := old.started_at; v_paused_at := old.paused_at; v_paused_total := old.paused_total_sec; v_ended := old.ended_at; v_published := old.published_at;
  end if;

  if new.status is distinct from old.status then
    if not priv and not (
      (old.status = 'scheduled' and new.status in ('running', 'cancelled')) or
      (old.status = 'running' and new.status in ('paused', 'ended', 'cancelled')) or
      (old.status = 'paused' and new.status in ('running', 'ended', 'cancelled')) or
      (old.status = 'ended' and new.status in ('under_review', 'cancelled')) or
      (old.status = 'under_review' and new.status in ('cancelled')) or
      (old.status = 'published' and new.status = 'under_review')
    ) then
      raise exception 'ILLEGAL_HEAT_TRANSITION: % -> %', old.status, new.status;
    end if;

    if old.status = 'scheduled' and new.status = 'running' then
      v_started := now();
    elsif old.status = 'running' and new.status = 'paused' then
      v_paused_at := now();
    elsif old.status = 'paused' and new.status = 'running' then
      v_paused_total := old.paused_total_sec + greatest(0, ceil(extract(epoch from (now() - coalesce(old.paused_at, now()))))::int);
      v_paused_at := null;
    elsif new.status = 'ended' and old.status in ('running', 'paused') then
      if old.status = 'paused' then
        v_ended := coalesce(old.paused_at, now());
      else
        v_end := old.started_at + make_interval(secs => old.duration_sec + old.paused_total_sec);
        v_ended := least(now(), coalesce(v_end, now()));
      end if;
    elsif new.status = 'published' then
      v_published := now();
    end if;

    -- privileged callers (publish, seeds, tests) may set a column explicitly; everyone else gets the computed value
    if not priv or new.started_at is not distinct from old.started_at then new.started_at := v_started; end if;
    if not priv or new.paused_at is not distinct from old.paused_at then new.paused_at := v_paused_at; end if;
    if not priv or new.paused_total_sec is not distinct from old.paused_total_sec then new.paused_total_sec := v_paused_total; end if;
    if not priv or new.ended_at is not distinct from old.ended_at then new.ended_at := v_ended; end if;
    if not priv or new.published_at is not distinct from old.published_at then new.published_at := v_published; end if;
  end if;
  return new;
end $$;

create trigger b_heats_guard before update on public.heats for each row execute function private.heats_guard();

-- ---------------------------------------------------------------- immutability (published results, audit trail)
create or replace function private.reject_change() returns trigger
language plpgsql as $$
begin
  if tg_op = 'DELETE' and current_setting('app.allow_purge', true) = 'on' then
    return old;
  end if;
  raise exception 'APPEND_ONLY: % on % is not allowed', tg_op, tg_table_name;
end $$;

create trigger a_append_only before update or delete on public.heat_results for each row execute function private.reject_change();
create trigger a_append_only before update or delete on public.audit_log for each row execute function private.reject_change();


-- ===== migration 20260929100300_audit.sql =====
-- Phase 3 / step 3: audit trigger. Who (user + seat), what, before, after, when, reason.
-- The reason and a friendlier action name arrive from the privileged functions through
-- transaction-local settings (app.reason, app.audit_action). Secrets are never copied into the log.
create or replace function private.audit_row() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  v_old jsonb := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) end;
  v_new jsonb := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) end;
  v_event uuid; v_seat uuid; v_action text;
begin
  v_old := v_old - 'pin_hash' - 'qr_token_hash';
  v_new := v_new - 'pin_hash' - 'qr_token_hash';
  v_event := (coalesce(v_new, v_old) ->> 'event_id')::uuid;
  select s.id into v_seat from public.judge_seats s where s.event_id = v_event and s.auth_user_id = auth.uid() and s.active limit 1;
  v_action := coalesce(nullif(current_setting('app.audit_action', true), ''), lower(tg_op));
  insert into public.audit_log (event_id, actor_user_id, actor_seat_id, action, table_name, row_id, before, after, reason)
  values (v_event, auth.uid(), v_seat, v_action, tg_table_name, (coalesce(v_new, v_old) ->> 'id')::uuid, v_old, v_new,
          nullif(current_setting('app.reason', true), ''));
  return null;
end $$;

do $$
declare t text;
begin
  foreach t in array array['trick_attempts','trick_scores','impression_scores','penalties','heat_results','judge_seats'] loop
    execute format('create trigger z_audit after insert or update or delete on public.%I for each row execute function private.audit_row()', t);
  end loop;
end $$;

-- Heats: only status / manual-override changes are worth a line (the live counter changes constantly).
create trigger z_audit after update on public.heats for each row
  when (old.status is distinct from new.status or old.manual_override is distinct from new.manual_override)
  execute function private.audit_row();


-- ===== migration 20260929100400_rls.sql =====
-- Phase 3 / step 4: Row Level Security on every table, least-privilege grants, safe views.
-- Rule of thumb: the database says who may do what; the app only asks.

-- ---------------------------------------------------------------- helper functions (security definer, so policies never recurse)
create or replace function private.is_org_member(p_org uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.memberships m where m.organisation_id = p_org and m.user_id = auth.uid());
$$;

create or replace function private.is_org_admin(p_org uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.memberships m where m.organisation_id = p_org and m.user_id = auth.uid() and m.role in ('owner', 'admin'));
$$;

create or replace function private.is_event_organiser(p_event uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.events e join public.memberships m on m.organisation_id = e.organisation_id
    where e.id = p_event and m.user_id = auth.uid());
$$;

create or replace function private.seat_id(p_event uuid) returns uuid
language sql stable security definer set search_path = '' as $$
  select s.id from public.judge_seats s
  where s.event_id = p_event and s.auth_user_id = auth.uid() and s.active and s.status = 'active' limit 1;
$$;

create or replace function private.seat_role(p_event uuid) returns text
language sql stable security definer set search_path = '' as $$
  select s.role from public.judge_seats s
  where s.event_id = p_event and s.auth_user_id = auth.uid() and s.active and s.status = 'active' limit 1;
$$;

create or replace function private.has_seat(p_event uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select private.seat_id(p_event) is not null;
$$;

create or replace function private.event_is_public(p_event uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.events e where e.id = p_event and e.status in ('published', 'live', 'complete'));
$$;

-- "ended" also covers a running heat whose timer has run out (no server process is needed to notice)
create or replace function private.heat_effective_status(p_heat uuid) returns text
language sql stable security definer set search_path = '' as $$
  select case when h.status = 'running' and h.started_at is not null
              and now() >= h.started_at + make_interval(secs => h.duration_sec + h.paused_total_sec)
         then 'ended' else h.status end
  from public.heats h where h.id = p_heat;
$$;

-- Setting for a division: the division's own override wins (even an explicit null = "unlimited"), else the scoring model.
create or replace function private.division_heat_setting(p_division uuid, p_key text) returns jsonb
language sql stable security definer set search_path = '' as $$
  select case when d.scoring_overrides -> 'heat' ? p_key then d.scoring_overrides -> 'heat' -> p_key else m.json -> 'heat' -> p_key end
  from public.divisions d left join public.scoring_models m on m.id = d.scoring_model_id
  where d.id = p_division;
$$;

-- May the calling judge write a mark for this heat right now? Panel member + heat running/paused (trick marks) or
-- ended within the grace period (trick and impression marks).
create or replace function private.judge_can_write(p_heat uuid, p_impression boolean) returns boolean
language plpgsql stable security definer set search_path = '' as $$
declare
  h public.heats; v_eff text; v_end timestamptz; v_grace int;
begin
  select * into h from public.heats where id = p_heat;
  if not found then return false; end if;
  if not exists (
    select 1 from public.divisions d
    join public.panel_members pm on pm.panel_id = d.panel_id
    join public.judge_seats s on s.id = pm.judge_seat_id
    where d.id = h.division_id and s.auth_user_id = auth.uid() and s.active and s.status = 'active'
  ) then return false; end if;
  v_eff := private.heat_effective_status(p_heat);
  if not p_impression and v_eff in ('running', 'paused') then return true; end if;
  if v_eff = 'ended' then
    v_end := coalesce(h.ended_at, h.started_at + make_interval(secs => h.duration_sec + h.paused_total_sec));
    select coalesce((e.settings ->> 'judgeGraceSec')::int, 180) into v_grace from public.events e where e.id = h.event_id;
    return v_end is not null and now() < v_end + make_interval(secs => v_grace);
  end if;
  return false;
end $$;

grant execute on all functions in schema private to anon, authenticated, service_role;

-- ---------------------------------------------------------------- privileges: start from nothing, grant only what is needed
revoke all on all tables in schema public from anon, authenticated;
revoke all on all functions in schema public from public, anon, authenticated;
alter default privileges for role postgres in schema public revoke all on tables from anon, authenticated;
alter default privileges for role postgres in schema public revoke execute on functions from public, anon, authenticated;

-- public reading (row filters decide what is really visible)
grant select on public.divisions, public.rounds, public.heats, public.heat_slots, public.heat_results, public.schedule_plans,
  public.wind_calls, public.scoring_models, public.format_templates, public.trick_vocabularies to anon, authenticated;
grant select (id, organisation_id, name, slug, location, timezone, start_date, end_date, status, settings, branding, created_at, updated_at)
  on public.events to anon, authenticated;

-- signed-in users (organisers and officials): row policies below narrow this further
grant select on public.organisations, public.memberships, public.panels, public.panel_members, public.trick_attempts,
  public.trick_scores, public.impression_scores, public.audit_log to authenticated;
grant update (name, branding) on public.organisations to authenticated;
grant insert (organisation_id, name, slug, location, timezone, start_date, end_date, status, settings, branding) on public.events to authenticated;
grant update (name, slug, location, timezone, start_date, end_date, status, settings, branding) on public.events to authenticated;
grant delete on public.events to authenticated;
grant insert, update, delete on public.divisions, public.rounds, public.heats, public.heat_slots, public.entries, public.riders,
  public.panels, public.panel_members, public.schedule_plans, public.wind_calls, public.penalties,
  public.scoring_models, public.format_templates, public.trick_vocabularies to authenticated;
grant select on public.entries, public.riders, public.penalties to authenticated;
-- hashes are readable by nobody but the server
grant select (id, event_id, name, role, auth_user_id, bound_at, device_label, active, scores, spotter_assignment, status, locked, created_at, updated_at)
  on public.judge_seats to authenticated;
grant insert (event_id, name, role, device_label, active, scores, spotter_assignment, status) on public.judge_seats to authenticated;
grant update (name, role, device_label, active, scores, spotter_assignment, status, locked) on public.judge_seats to authenticated;
grant delete on public.judge_seats to authenticated;
-- marks are written through submit_* functions that run as the caller
grant insert, update on public.trick_scores, public.impression_scores to authenticated;
grant select on public.heat_results to authenticated;

-- ---------------------------------------------------------------- RLS on everything
do $$
declare t text;
begin
  for t in select tablename from pg_tables where schemaname = 'public' loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;
-- join_attempts: RLS on, no policies, no grants = service role only.

-- ---------------------------------------------------------------- policies
-- organisations / memberships
create policy org_read on public.organisations for select to authenticated using (private.is_org_member(id));
create policy org_update on public.organisations for update to authenticated using (private.is_org_admin(id)) with check (private.is_org_admin(id));
create policy member_read on public.memberships for select to authenticated using (user_id = auth.uid() or private.is_org_admin(organisation_id));

-- events
create policy public_read on public.events for select to anon, authenticated using (status in ('published', 'live', 'complete'));
create policy org_read on public.events for select to authenticated using (private.is_org_member(organisation_id));
create policy seat_read on public.events for select to authenticated using (private.has_seat(id));
create policy org_insert on public.events for insert to authenticated with check (private.is_org_member(organisation_id));
create policy org_update on public.events for update to authenticated using (private.is_org_member(organisation_id)) with check (private.is_org_member(organisation_id));
create policy org_delete on public.events for delete to authenticated using (private.is_org_member(organisation_id));

-- riders (personal data: organisers only; everyone else uses v_entries)
create policy org_all on public.riders for all to authenticated using (private.is_org_member(organisation_id)) with check (private.is_org_member(organisation_id));

-- presets
create policy read_models on public.scoring_models for select to anon, authenticated
  using (organisation_id is null or private.is_org_member(organisation_id) or exists (select 1 from public.divisions d where d.scoring_model_id = scoring_models.id));
create policy org_write_models on public.scoring_models for all to authenticated
  using (organisation_id is not null and private.is_org_member(organisation_id)) with check (organisation_id is not null and private.is_org_member(organisation_id));
create policy read_formats on public.format_templates for select to anon, authenticated
  using (organisation_id is null or private.is_org_member(organisation_id) or exists (select 1 from public.divisions d where d.format_template_id = format_templates.id));
create policy org_write_formats on public.format_templates for all to authenticated
  using (organisation_id is not null and private.is_org_member(organisation_id)) with check (organisation_id is not null and private.is_org_member(organisation_id));
create policy read_vocab on public.trick_vocabularies for select to anon, authenticated
  using ((organisation_id is null and event_id is null) or (event_id is not null and (private.event_is_public(event_id) or private.has_seat(event_id) or private.is_event_organiser(event_id)))
         or (organisation_id is not null and private.is_org_member(organisation_id)));
create policy org_write_vocab on public.trick_vocabularies for all to authenticated
  using (organisation_id is not null and private.is_org_member(organisation_id)) with check (organisation_id is not null and private.is_org_member(organisation_id));

-- event-scoped configuration: organisers full access; officials of the event read; the public reads published events
do $$
declare t text;
begin
  foreach t in array array['divisions','rounds','heats','heat_slots','panels','panel_members','schedule_plans','wind_calls','entries','penalties'] loop
    execute format('create policy org_all on public.%I for all to authenticated using (private.is_event_organiser(event_id)) with check (private.is_event_organiser(event_id))', t);
  end loop;
  foreach t in array array['divisions','rounds','heats','heat_slots','panels','panel_members','schedule_plans','wind_calls','penalties','trick_attempts','heat_results'] loop
    execute format('create policy seat_read on public.%I for select to authenticated using (private.has_seat(event_id))', t);
  end loop;
  foreach t in array array['divisions','rounds','heats','heat_slots','heat_results','wind_calls'] loop
    execute format('create policy public_read on public.%I for select to anon, authenticated using (private.event_is_public(event_id))', t);
  end loop;
  foreach t in array array['trick_attempts','trick_scores','impression_scores','heat_results','audit_log'] loop
    execute format('create policy org_read on public.%I for select to authenticated using (private.is_event_organiser(event_id))', t);
  end loop;
end $$;
create policy public_read on public.schedule_plans for select to anon, authenticated using (active and private.event_is_public(event_id));

-- the head judge runs the heat: timer buttons, slot flags, wind calls, penalties
create policy head_update on public.heats for update to authenticated using (private.seat_role(event_id) = 'head') with check (private.seat_role(event_id) = 'head');
create policy head_update on public.heat_slots for update to authenticated using (private.seat_role(event_id) = 'head') with check (private.seat_role(event_id) = 'head');
create policy head_insert on public.wind_calls for insert to authenticated with check (private.seat_role(event_id) = 'head');
create policy head_write on public.penalties for all to authenticated using (private.seat_role(event_id) = 'head') with check (private.seat_role(event_id) = 'head');
create policy head_read on public.audit_log for select to authenticated using (private.seat_role(event_id) = 'head');

-- marks: a judge sees and writes only their own; head judge and announcer read everything
do $$
declare t text;
begin
  foreach t in array array['trick_scores','impression_scores'] loop
    execute format('create policy own_read on public.%I for select to authenticated using (judge_seat_id = private.seat_id(event_id))', t);
    execute format('create policy staff_read on public.%I for select to authenticated using (private.seat_role(event_id) in (''head'', ''announcer''))', t);
  end loop;
end $$;
create policy own_insert on public.trick_scores for insert to authenticated
  with check (judge_seat_id = private.seat_id(event_id) and private.judge_can_write(heat_id, false));
create policy own_update on public.trick_scores for update to authenticated
  using (judge_seat_id = private.seat_id(event_id)) with check (judge_seat_id = private.seat_id(event_id) and private.judge_can_write(heat_id, false));
create policy own_insert on public.impression_scores for insert to authenticated
  with check (judge_seat_id = private.seat_id(event_id) and private.judge_can_write(heat_id, true));
create policy own_update on public.impression_scores for update to authenticated
  using (judge_seat_id = private.seat_id(event_id)) with check (judge_seat_id = private.seat_id(event_id) and private.judge_can_write(heat_id, true));

-- seats
create policy org_all on public.judge_seats for all to authenticated using (private.is_event_organiser(event_id)) with check (private.is_event_organiser(event_id));
create policy head_read on public.judge_seats for select to authenticated using (private.seat_role(event_id) = 'head');
create policy own_read on public.judge_seats for select to authenticated using (auth_user_id = auth.uid());

-- ---------------------------------------------------------------- the rider chip view: names and identifiers, never contact details
create view public.v_entries with (security_invoker = false) as
select e.id, e.event_id, e.division_id, e.seed, e.status, e.identifiers,
       r.first_name, r.last_name, r.nationality, r.sponsor, r.photo_url
from public.entries e join public.riders r on r.id = e.rider_id
where private.is_event_organiser(e.event_id) or private.has_seat(e.event_id)
   or (private.event_is_public(e.event_id) and e.status in ('confirmed', 'withdrawn', 'no_show'));
grant select on public.v_entries to anon, authenticated;


-- ===== migration 20260929100500_realtime.sql =====
-- Phase 3 / step 5: Realtime for official screens (public pages poll instead, docs/05 §12 decision 4).
-- Full replica identity so filtered UPDATE/DELETE events (filter heat_id=eq.…) carry the old row too.
alter publication supabase_realtime add table public.heats, public.heat_slots, public.trick_attempts, public.trick_scores,
  public.impression_scores, public.penalties, public.heat_results, public.schedule_plans, public.wind_calls;
alter table public.heats replica identity full;
alter table public.heat_slots replica identity full;
alter table public.trick_attempts replica identity full;
alter table public.trick_scores replica identity full;
alter table public.impression_scores replica identity full;
alter table public.penalties replica identity full;


-- ===== migration 20260929100600_functions.sql =====
-- Phase 3 / step 6: the only doors into protected data. Every function states who may call it.
-- Errors are plain codes the app can show: ATTEMPT_CAP_REACHED, HEAT_NOT_RUNNING, RIDER_NOT_IN_HEAT, ...

-- ---------------------------------------------------------------- attempts
create or replace function public.add_attempt(
  p_heat uuid, p_entry uuid, p_client_key uuid, p_status text,
  p_direction text default null, p_category_key text default null, p_trick_name text default null,
  p_trick_parts jsonb default '{}', p_height_m numeric default null,
  p_input_method text default 'builder', p_raw_text text default null, p_override_reason text default null
) returns public.trick_attempts
language plpgsql security definer set search_path = '' as $$
declare
  h public.heats; ev public.events; slot public.heat_slots; v_row public.trick_attempts;
  v_role text; v_seat uuid; v_org boolean; v_privileged boolean; v_eff text;
  v_cap int; v_used int; v_seq int; v_dup uuid; v_window int; v_over boolean := false;
begin
  select * into h from public.heats where id = p_heat;
  if not found then raise exception 'HEAT_NOT_FOUND'; end if;
  select * into ev from public.events where id = h.event_id;
  v_org := private.is_event_organiser(h.event_id);
  v_seat := private.seat_id(h.event_id);
  v_role := private.seat_role(h.event_id);
  if not v_org and not (v_role in ('spotter', 'head') or (v_role = 'judge' and coalesce((ev.settings ->> 'judgesMayLogAttempts')::boolean, false))) then
    raise exception 'NOT_ALLOWED';
  end if;
  v_privileged := v_org or v_role = 'head';

  -- safe retry: the same client_key returns the attempt that already exists
  select * into v_row from public.trick_attempts where client_key = p_client_key;
  if found then
    if v_row.heat_id <> p_heat then raise exception 'CLIENT_KEY_REUSED'; end if;
    return v_row;
  end if;

  v_eff := private.heat_effective_status(p_heat);
  if not (v_eff = 'running' or (v_privileged and v_eff in ('paused', 'ended', 'under_review'))) then
    raise exception 'HEAT_NOT_RUNNING';
  end if;

  select * into slot from public.heat_slots where heat_id = p_heat and entry_id = p_entry;
  if not found then raise exception 'RIDER_NOT_IN_HEAT'; end if;
  if slot.modifier is not null or slot.flagged_out then raise exception 'RIDER_NOT_RIDING'; end if;

  -- one rider, one lock: two phones cannot both take the last place
  perform pg_advisory_xact_lock(hashtextextended(p_heat::text || p_entry::text, 0));
  select * into v_row from public.trick_attempts where client_key = p_client_key;
  if found then return v_row; end if;

  v_cap := (private.division_heat_setting(h.division_id, 'maxAttemptsPerRider') #>> '{}')::int;
  select count(*) into v_used from public.trick_attempts a where a.heat_id = p_heat and a.entry_id = p_entry and a.deleted_at is null;
  if v_cap is not null and v_used >= v_cap then
    if p_override_reason is null or not v_privileged then raise exception 'ATTEMPT_CAP_REACHED'; end if;
    if btrim(p_override_reason) = '' then raise exception 'OVERRIDE_REASON_REQUIRED'; end if;
    v_over := true;
  end if;

  select coalesce(max(a.seq), 0) + 1 into v_seq from public.trick_attempts a where a.heat_id = p_heat and a.entry_id = p_entry;

  -- two different spotters logging the same rider within the window: flag it for the head judge, never drop it
  v_window := coalesce((private.division_heat_setting(h.division_id, 'duplicateWindowSec') #>> '{}')::int, 20);
  select a.id into v_dup from public.trick_attempts a
   where a.heat_id = p_heat and a.entry_id = p_entry and a.deleted_at is null
     and a.created_by_seat is distinct from v_seat and a.created_at > now() - make_interval(secs => v_window)
   order by a.created_at desc limit 1;

  if v_over then
    perform set_config('app.audit_action', 'attempt_cap_override', true);
    perform set_config('app.reason', p_override_reason, true);
  end if;
  insert into public.trick_attempts (heat_id, entry_id, seq, client_key, status, direction, category_key, trick_name, trick_parts,
                                     height_m, created_by_seat, input_method, raw_text, possible_duplicate_of, event_id)
  values (p_heat, p_entry, v_seq, p_client_key, p_status, p_direction, p_category_key, p_trick_name, coalesce(p_trick_parts, '{}'),
          p_height_m, v_seat, coalesce(p_input_method, 'builder'), p_raw_text, v_dup, h.event_id)
  returning * into v_row;
  perform set_config('app.audit_action', '', true);
  perform set_config('app.reason', '', true);
  return v_row;
end $$;

create or replace function public.delete_attempt(p_attempt uuid, p_reason text) returns public.trick_attempts
language plpgsql security definer set search_path = '' as $$
declare a public.trick_attempts; h public.heats; v_row public.trick_attempts;
begin
  select * into a from public.trick_attempts where id = p_attempt;
  if not found then raise exception 'ATTEMPT_NOT_FOUND'; end if;
  if not (private.is_event_organiser(a.event_id) or private.seat_role(a.event_id) = 'head') then raise exception 'NOT_ALLOWED'; end if;
  if p_reason is null or btrim(p_reason) = '' then raise exception 'REASON_REQUIRED'; end if;
  select * into h from public.heats where id = a.heat_id;
  if h.status = 'published' then raise exception 'HEAT_PUBLISHED'; end if;
  if a.deleted_at is not null then return a; end if;
  perform set_config('app.audit_action', 'attempt_deleted', true);
  perform set_config('app.reason', p_reason, true);
  update public.trick_attempts set deleted_at = now(), deleted_by = auth.uid() where id = p_attempt returning * into v_row;
  perform set_config('app.audit_action', '', true);
  perform set_config('app.reason', '', true);
  return v_row;
end $$;

-- "5 / 7" counters for the phones (same count the cap uses)
create or replace function public.attempt_counts(p_heat uuid) returns table (entry_id uuid, used int, cap int)
language plpgsql stable security definer set search_path = '' as $$
declare h public.heats; v_cap int;
begin
  select * into h from public.heats where id = p_heat;
  if not found or not (private.has_seat(h.event_id) or private.is_event_organiser(h.event_id)) then raise exception 'NOT_ALLOWED'; end if;
  v_cap := (private.division_heat_setting(h.division_id, 'maxAttemptsPerRider') #>> '{}')::int;
  return query
    select s.entry_id, (select count(*)::int from public.trick_attempts a where a.heat_id = p_heat and a.entry_id = s.entry_id and a.deleted_at is null), v_cap
    from public.heat_slots s where s.heat_id = p_heat and s.entry_id is not null;
end $$;

-- ---------------------------------------------------------------- marks (run as the caller: Row Level Security decides)
create or replace function public.submit_trick_score(
  p_attempt uuid, p_criteria jsonb, p_score numeric, p_missed boolean, p_flag text, p_client_key uuid, p_client_rev bigint
) returns public.trick_scores
language plpgsql security invoker set search_path = '' as $$
declare a public.trick_attempts; r public.trick_scores; v_seat uuid;
begin
  select * into a from public.trick_attempts where id = p_attempt;
  if not found then raise exception 'ATTEMPT_NOT_FOUND'; end if;
  v_seat := private.seat_id(a.event_id);
  if v_seat is null then raise exception 'NOT_ALLOWED'; end if;
  insert into public.trick_scores as ts (attempt_id, judge_seat_id, criteria, score, missed, flag, client_key, client_rev, edited_by, event_id, heat_id)
  values (p_attempt, v_seat, coalesce(p_criteria, '{}'), case when p_missed then null else p_score end, coalesce(p_missed, false), p_flag,
          p_client_key, p_client_rev, auth.uid(), a.event_id, a.heat_id)
  on conflict (attempt_id, judge_seat_id) do update
    set criteria = excluded.criteria, score = excluded.score, missed = excluded.missed, flag = excluded.flag,
        client_key = excluded.client_key, client_rev = excluded.client_rev, version = ts.version + 1, edited_by = auth.uid()
    where excluded.client_rev > ts.client_rev
  returning * into r;
  if r.id is null then -- an older queued edit arrived late: keep the newer mark
    select * into r from public.trick_scores where attempt_id = p_attempt and judge_seat_id = v_seat;
  end if;
  return r;
end $$;

create or replace function public.submit_impression(p_heat uuid, p_entry uuid, p_value numeric, p_client_key uuid, p_client_rev bigint)
returns public.impression_scores
language plpgsql security invoker set search_path = '' as $$
declare h public.heats; r public.impression_scores; v_seat uuid;
begin
  select * into h from public.heats where id = p_heat;
  if not found then raise exception 'HEAT_NOT_FOUND'; end if;
  v_seat := private.seat_id(h.event_id);
  if v_seat is null then raise exception 'NOT_ALLOWED'; end if;
  insert into public.impression_scores as i (heat_id, entry_id, judge_seat_id, value, client_key, client_rev, event_id)
  values (p_heat, p_entry, v_seat, p_value, p_client_key, p_client_rev, h.event_id)
  on conflict (heat_id, entry_id, judge_seat_id) do update
    set value = excluded.value, client_key = excluded.client_key, client_rev = excluded.client_rev
    where excluded.client_rev > i.client_rev
  returning * into r;
  if r.id is null then
    select * into r from public.impression_scores where heat_id = p_heat and entry_id = p_entry and judge_seat_id = v_seat;
  end if;
  return r;
end $$;

-- ---------------------------------------------------------------- public live view (polled every 5-10 s; no judge identities)
create or replace function public.get_public_live_heat(p_heat uuid) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare h public.heats; ev public.events;
begin
  select * into h from public.heats where id = p_heat;
  if not found then return jsonb_build_object('allowed', false); end if;
  select * into ev from public.events where id = h.event_id;
  if ev.status not in ('published', 'live', 'complete') or coalesce(ev.settings ->> 'publicLiveScores', 'after_publish') <> 'live'
     or h.status in ('scheduled', 'cancelled') then
    return jsonb_build_object('allowed', false);
  end if;
  return jsonb_build_object(
    'allowed', true,
    'poll_sec', coalesce((ev.settings ->> 'livePollSec')::int, 7),
    'heat', jsonb_build_object('id', h.id, 'status', h.status, 'effective_status', private.heat_effective_status(h.id), 'started_at', h.started_at,
             'duration_sec', h.duration_sec, 'paused_at', h.paused_at, 'paused_total_sec', h.paused_total_sec, 'ended_at', h.ended_at,
             'live_rev', h.live_rev, 'server_now', now()),
    'slots', coalesce((select jsonb_agg(jsonb_build_object('position', s.position, 'entry_id', s.entry_id, 'vest_colour', s.vest_colour,
             'modifier', s.modifier, 'flagged_out', s.flagged_out) order by s.position) from public.heat_slots s where s.heat_id = h.id), '[]'),
    'attempts', coalesce((select jsonb_agg(jsonb_build_object('id', a.id, 'entry_id', a.entry_id, 'seq', a.seq, 'direction', a.direction,
             'category_key', a.category_key, 'trick_name', a.trick_name, 'status', a.status, 'height_m', a.height_m,
             'possible_duplicate_of', a.possible_duplicate_of, 'created_at', a.created_at) order by a.created_at)
             from public.trick_attempts a where a.heat_id = h.id and a.deleted_at is null), '[]'),
    'scores', coalesce((select jsonb_agg(jsonb_build_object('attempt_id', t.attempt_id, 'seat_no', pm.seat_no, 'criteria', t.criteria,
             'score', t.score, 'missed', t.missed))
             from public.trick_scores t
             join public.trick_attempts a on a.id = t.attempt_id and a.deleted_at is null
             join public.divisions d on d.id = h.division_id
             join public.panel_members pm on pm.panel_id = d.panel_id and pm.judge_seat_id = t.judge_seat_id
             where t.heat_id = h.id), '[]'),
    'impressions', coalesce((select jsonb_agg(jsonb_build_object('entry_id', i.entry_id, 'seat_no', pm.seat_no, 'value', i.value))
             from public.impression_scores i
             join public.divisions d on d.id = h.division_id
             join public.panel_members pm on pm.panel_id = d.panel_id and pm.judge_seat_id = i.judge_seat_id
             where i.heat_id = h.id), '[]'),
    'penalties', coalesce((select jsonb_agg(jsonb_build_object('entry_id', p.entry_id, 'type', p.type, 'value', p.value))
             from public.penalties p where p.heat_id = h.id), '[]')
  );
end $$;

-- ---------------------------------------------------------------- PINs, QR tokens and joining (server only: service role)
create or replace function public.set_seat_pin(p_seat uuid, p_pin text) returns void
language plpgsql security definer set search_path = '' as $$
declare s public.judge_seats;
begin
  if p_pin !~ '^[0-9]{6}$' then raise exception 'PIN_MUST_BE_6_DIGITS'; end if;
  select * into s from public.judge_seats where id = p_seat;
  if not found then raise exception 'SEAT_NOT_FOUND'; end if;
  if exists (select 1 from public.judge_seats o where o.event_id = s.event_id and o.id <> s.id and o.pin_hash is not null
             and o.pin_hash = extensions.crypt(p_pin, o.pin_hash)) then
    raise exception 'PIN_IN_USE';
  end if;
  perform set_config('app.audit_action', 'pin_set', true);
  update public.judge_seats set pin_hash = extensions.crypt(p_pin, extensions.gen_salt('bf')) where id = p_seat;
  perform set_config('app.audit_action', '', true);
end $$;

create or replace function public.set_seat_qr(p_seat uuid, p_token text, p_expires timestamptz) returns void
language plpgsql security definer set search_path = '' as $$
begin
  perform set_config('app.audit_action', 'qr_set', true);
  update public.judge_seats set qr_token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex'), qr_token_expires_at = p_expires where id = p_seat;
  perform set_config('app.audit_action', '', true);
end $$;

-- Failures are returned (not raised) so that the failure log survives the call and rate limiting works.
create or replace function private.join_rate_limited(p_event uuid, p_ip text) returns boolean
language sql stable security definer set search_path = '' as $$
  select (select count(*) from public.join_attempts j where j.event_id = p_event and j.ip = p_ip and not j.ok and j.at > now() - interval '10 minutes') >= 10
      or (select count(*) from public.join_attempts j where j.event_id = p_event and not j.ok and j.at > now() - interval '10 minutes') >= 100;
$$;

create or replace function private.bind_seat(p_seat public.judge_seats, p_user uuid, p_ip text, p_how text) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare v_rebound boolean;
begin
  if p_seat.locked and p_seat.auth_user_id is not null and p_seat.auth_user_id <> p_user then
    return jsonb_build_object('ok', false, 'error', 'SEAT_LOCKED');
  end if;
  v_rebound := p_seat.auth_user_id is not null and p_seat.auth_user_id <> p_user;
  perform set_config('app.audit_action', 'seat_bound', true);
  perform set_config('app.reason', 'joined by ' || p_how, true);
  -- one login holds one seat per event: free any seat this login held before
  update public.judge_seats set auth_user_id = null where event_id = p_seat.event_id and auth_user_id = p_user and id <> p_seat.id;
  update public.judge_seats set auth_user_id = p_user, bound_at = now() where id = p_seat.id;
  perform set_config('app.audit_action', '', true);
  perform set_config('app.reason', '', true);
  insert into public.join_attempts (event_id, ip, seat_id, ok) values (p_seat.event_id, p_ip, p_seat.id, true);
  return jsonb_build_object('ok', true, 'seat_id', p_seat.id, 'event_id', p_seat.event_id, 'role', p_seat.role, 'name', p_seat.name, 'rebound', v_rebound);
end $$;

create or replace function public.bind_seat_by_pin(p_event uuid, p_pin text, p_user uuid, p_ip text) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare s public.judge_seats;
begin
  if private.join_rate_limited(p_event, p_ip) then return jsonb_build_object('ok', false, 'error', 'RATE_LIMITED'); end if;
  select * into s from public.judge_seats x
   where x.event_id = p_event and x.active and x.status = 'active' and x.pin_hash is not null and x.pin_hash = extensions.crypt(p_pin, x.pin_hash) limit 1;
  if not found then
    insert into public.join_attempts (event_id, ip, ok) values (p_event, p_ip, false);
    return jsonb_build_object('ok', false, 'error', 'INVALID_PIN');
  end if;
  return private.bind_seat(s, p_user, p_ip, 'PIN');
end $$;

create or replace function public.bind_seat_by_token(p_event uuid, p_token text, p_user uuid, p_ip text) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare s public.judge_seats; v jsonb;
begin
  if private.join_rate_limited(p_event, p_ip) then return jsonb_build_object('ok', false, 'error', 'RATE_LIMITED'); end if;
  select * into s from public.judge_seats x
   where x.event_id = p_event and x.active and x.status = 'active' and x.qr_token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
     and (x.qr_token_expires_at is null or x.qr_token_expires_at > now()) limit 1;
  if not found then
    insert into public.join_attempts (event_id, ip, ok) values (p_event, p_ip, false);
    return jsonb_build_object('ok', false, 'error', 'INVALID_TOKEN');
  end if;
  v := private.bind_seat(s, p_user, p_ip, 'QR code');
  if (v ->> 'ok')::boolean then -- single use
    update public.judge_seats set qr_token_hash = null, qr_token_expires_at = null where id = s.id;
  end if;
  return v;
end $$;

-- ---------------------------------------------------------------- maintenance (service role only)
-- Deleting an organisation with published results is otherwise impossible (results and audit are append-only).
create or replace function public.purge_organisation(p_org uuid) returns void
language plpgsql security definer set search_path = '' as $$
declare v_events uuid[];
begin
  select coalesce(array_agg(id), '{}') into v_events from public.events where organisation_id = p_org;
  perform set_config('app.allow_purge', 'on', true);
  delete from public.organisations where id = p_org;
  delete from public.audit_log where event_id = any (v_events);
  perform set_config('app.allow_purge', 'off', true);
end $$;

create or replace function public.rls_coverage()
returns table (table_name text, rls_enabled boolean, policy_count int, anon_can_select boolean, anon_can_write boolean, authenticated_can_write boolean)
language sql stable security definer set search_path = '' as $$
  select c.relname::text, c.relrowsecurity,
         (select count(*)::int from pg_policies p where p.schemaname = 'public' and p.tablename = c.relname),
         has_any_column_privilege('anon', c.oid, 'select'),
         has_table_privilege('anon', c.oid, 'insert') or has_table_privilege('anon', c.oid, 'update') or has_table_privilege('anon', c.oid, 'delete'),
         has_table_privilege('authenticated', c.oid, 'insert') or has_table_privilege('authenticated', c.oid, 'update') or has_table_privilege('authenticated', c.oid, 'delete')
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r' order by c.relname;
$$;

-- ---------------------------------------------------------------- who may call what
revoke all on function
  public.add_attempt, public.delete_attempt, public.attempt_counts, public.submit_trick_score, public.submit_impression,
  public.get_public_live_heat, public.set_seat_pin, public.set_seat_qr, public.bind_seat_by_pin, public.bind_seat_by_token,
  public.purge_organisation, public.rls_coverage from public, anon, authenticated;
grant execute on function public.add_attempt, public.delete_attempt, public.attempt_counts, public.submit_trick_score, public.submit_impression to authenticated;
grant execute on function public.get_public_live_heat to anon, authenticated;
grant execute on function public.set_seat_pin, public.set_seat_qr, public.bind_seat_by_pin, public.bind_seat_by_token,
  public.purge_organisation, public.rls_coverage to service_role;
revoke all on function private.join_rate_limited, private.bind_seat from public, anon, authenticated;

