/**
 * What each refusal or error sentence means and how to fix it: the source of the manual's errors page (docs/manual/errors.md) and of the
 * "A sentence on screen" part of the troubleshooting page. `npm run manual:generate` writes both from this file and from ui-copy.ts.
 * A sentence with no note of its own takes its part's meaning and fix (SECTIONS). Keep each line plain: what happened, what to do.
 */

export interface Section {
  /** The heading on the troubleshooting page. */
  title: string;
  /** Where the sentence shows. */
  where: string;
  meaning: string;
  fix: string;
}

export interface Note {
  w?: string;
  m?: string;
  f?: string;
}

const RETRY = "Nothing was saved. Check the connection and press the button again. If it keeps failing, note the time and tell the owner (the server log names the cause).";

export const SECTIONS: Record<string, Section> = {
  notFound: { title: "Public pages", where: "Any public address that is not available", meaning: "The address is wrong, or the event is a draft, a simulation, archived, or its organisation is archived.", fix: "Check the address. As organiser: Event step → tick Published, and make sure the event is not a simulation or archived." },
  join: { title: "Officials joining", where: "Join page (/join or /e/‹event›/join)", meaning: "Joining with the event code and PIN (or QR card) did not work.", fix: "Follow the sentence; the organiser can regenerate a PIN in the Officials step." },
  login: { title: "Organiser sign-in", where: "Organiser sign in (/org/login)", meaning: "Signing in did not work.", fix: "Follow the sentence. The link must be opened in the same browser that asked for it." },
  setPassword: { title: "Organiser sign-in", where: "Set or change password", meaning: "The password could not be set.", fix: "Follow the sentence." },
  seat: { title: "Officials joining", where: "Seat page (/seat)", meaning: "This phone is not connected to an active seat.", fix: "Join again with the PIN; if the seat is switched off, the organiser switches it on in the Officials step." },
  landing: { title: "Public pages", where: "Home page", meaning: "The home page could not do what was asked.", fix: "Follow the sentence." },
  eventLifecycle: { title: "Organiser: event list and Event step", where: "Delete or archive this event (platform owner only)", meaning: "The event could not be deleted or archived.", fix: "Follow the sentence. An event with published results can only be archived." },
  publicSite: { title: "Public pages", where: "Organisation page and event pages", meaning: "The event is not public.", fix: "As organiser: Event step → Published; not a simulation; not archived." },
  orgHome: { title: "Organiser: event list and Event step", where: "Events list (/org)", meaning: "This login belongs to no organisation.", fix: "The platform owner invites the login as organiser of an organisation (Admin → Organisations → Invite organiser)." },
  orgSettings: { title: "Organiser: organisation settings", where: "Organisation settings (/org/settings)", meaning: "The organisation settings could not be saved.", fix: "Follow the sentence. Only owners and admins of the organisation may save." },
  logo: { title: "Organiser: event list and Event step", where: "Any logo or sponsor picture field", meaning: "The picture was refused.", fix: "Use a PNG, JPEG or WebP file of at most 2 MB." },
  readiness: { title: "Organiser: Go live", where: "Go live checklist", meaning: "A seat has no PIN the screen can show.", fix: "Officials step → that seat → Regenerate PIN." },
  event: { title: "Organiser: event list and Event step", where: "Event step (step 1)", meaning: "The Event step could not be saved as it is.", fix: "Fix the highlighted field and press Save event again." },
  ident: { title: "Organiser: Rider label", where: "Event step → Rider identification, and Divisions → Rider label", meaning: "The rider identification scheme is not valid yet.", fix: "Fix the colour or field the sentence names, then save." },
  divisions: { title: "Organiser: Divisions", where: "Divisions step (step 2)", meaning: "The division change was refused.", fix: "Follow the sentence." },
  rules: { title: "Organiser: Divisions", where: "Divisions step → Scoring or Format tab", meaning: "The scoring or format panel needs something first.", fix: "Follow the sentence." },
  formatSimple: { title: "Organiser: Divisions", where: "Divisions step → Format tab", meaning: "The format's numbers do not fit together.", fix: "Change the highlighted number; the preview comes back when the format can run." },
  customBuilder: { title: "Organiser: Divisions", where: "Divisions step → Format tab → Custom ladder checker", meaning: "The ladder you are drawing has a problem the checker found.", fix: "Fix the red point it names; then Apply to draw is on." },
  ladder: { title: "Organiser: Divisions", where: "Format preview and Draw step", meaning: "This format cannot make a ladder for this number of riders.", fix: "Change the number of riders per heat, how many advance, or pick another format." },
  draw: { title: "Organiser: Draw", where: "Draw step (step 5)", meaning: "The draw could not be made or changed.", fix: "Follow the sentence." },
  builder: { title: "Organiser: Divisions", where: "Divisions step → Format tab → Custom ladder", meaning: "The custom ladder could not be applied to the draw.", fix: "Follow the sentence." },
  runOrder: { title: "Organiser: Run order", where: "Run order & timetable step (step 6)", meaning: "The run order (plan) could not be changed.", fix: "Follow the sentence." },
  presets: { title: "Organiser: Divisions", where: "Divisions step → Import a JSON file", meaning: "The file cannot be imported as a scoring preset or format.", fix: "Use a file exported with Export as JSON from the same tab." },
  admin: { title: "Platform owner (/admin)", where: "Admin screens (platform owner and staff)", meaning: "The admin action was refused.", fix: "Follow the sentence. Most admin changes need the platform owner role." },
  friendly: { title: "Organiser: Divisions", where: "Any settings form (More settings)", meaning: "A field holds a value it cannot take.", fix: "Type a value the sentence asks for." },
  slugLink: { title: "Organiser: event list and Event step", where: "Public link copy button", meaning: "The browser did not allow copying.", fix: "Select the link and copy it by hand." },
  riders: { title: "Organiser: Riders", where: "Riders step (step 3)", meaning: "The rider change was refused, or the rider list has a problem.", fix: "Follow the sentence." },
  trickBase: { title: "Organiser: Divisions", where: "Divisions step → Trick base tab", meaning: "The trick base change was refused.", fix: "Follow the sentence." },
  feedback: { title: "Feedback notes", where: "Note button and Feedback lists", meaning: "The note could not be saved or exported.", fix: "Follow the sentence." },
  officials: { title: "Organiser: Officials", where: "Officials step (step 4)", meaning: "The seat change was refused.", fix: "Follow the sentence." },
  registration: { title: "Rider registration", where: "Public registration page (/e/‹event›/register)", meaning: "The registration was not sent.", fix: "Follow the sentence." },
  live: { title: "Judge and spotter phones", where: "Judge and spotter screens", meaning: "The phone could not do what was asked.", fix: "Follow the sentence." },
  pub: { title: "Public pages", where: "Public event pages", meaning: "The page has nothing public to show.", fix: "As organiser: check Published, and that the rider is in a locked draw." },
  simulator: { title: "Simulator", where: "Simulator panel (/org/events/‹id›/simulate)", meaning: "The simulator could not do it.", fix: "Follow the sentence." },
  windCall: { title: "Organiser: Go live", where: "Wind call control (Go live and head console)", meaning: "The wind call was not changed.", fix: "Follow the sentence." },
  liveErrors: { title: "Head console, judge and spotter (database answers)", where: "Head console, judge and spotter screens, Go live quick actions", meaning: "The database refused the action and said why.", fix: "Follow the sentence; the dependency map names what must be true first." },
  judge: { title: "Judge and spotter phones", where: "Judge screen", meaning: "The judge's scores cannot be changed or sent right now.", fix: "Follow the sentence." },
  spotter: { title: "Judge and spotter phones", where: "Spotter screen", meaning: "The attempt was not logged or undone.", fix: "Follow the sentence." },
  crash: { title: "Pages that fail", where: "Any live page, organiser step or public page", meaning: "The page (or part of it) failed while loading; nothing was changed.", fix: "Press Try again. If it repeats, send the error reference (or the sentence) to the owner." },
  heatControl: { title: "Head console", where: "Head console run-order list", meaning: "No run order is active for today.", fix: "Run order step → pick today → Activate this plan." },
  headV2: { title: "Head console", where: "Head console top bar", meaning: "The console explains why the countdown or the start is not as expected.", fix: "Follow the sentence." },
  publish: { title: "Head console", where: "Head console → Publish", meaning: "Publish refused.", fix: "Follow the sentence." },
  reset: { title: "Resets", where: "Go live → Reset event… (and Restore in /admin)", meaning: "The reset or restore was refused; nothing was changed.", fix: "Follow the sentence." },
  resetParts: { title: "Resets", where: "Reset this division (Divisions), Clear actual times (Run order), Reset this heat (head console Heat menu)", meaning: "The reset was refused; nothing was changed.", fix: "Follow the sentence." },
  headLive: { title: "Head console", where: "Head console dialogs", meaning: "The head console needs a decision or a reason first.", fix: "Follow the sentence." },
  controlWhy: { title: "Grey buttons on the head console", where: "Under a grey button on the head console (laptop and phone)", meaning: "The button is off in this heat state.", fix: "Do what the sentence says, or pick another heat in the run order." },
  dashboard: { title: "Organiser: Go live", where: "Go live → Quick actions", meaning: "A quick action is off or refused.", fix: "Follow the sentence." },
};

export const NOTES: Record<string, Note> = {
  // ---- public
  "notFound.eventTitle": { m: "The event is private, unpublished, a simulation, archived, or the address is wrong. The page answers 404 on purpose.", f: "Event step → tick “Published” and Save event. A simulation event is never public; an archived event or organisation is hidden." },
  "notFound.pageTitle": { m: "No page has this address.", f: "Check the address; start from the home page." },
  "publicSite.eventNotFound": { m: "The organisation page has no such public event." },
  "pub.common.notFound": { m: "The public site has no event at this address (draft, simulation, archived, or wrong address)." },
  "pub.rider.notFound": { m: "That rider is not in a locked draw of a public event, or the address is old.", f: "Lock the division's draw; open the rider from the Results or Ladder page." },
  "landing.loadError": { m: "The home page could not read the event list (database asleep or unreachable).", f: "Wait a minute and reload. On the free plan the owner wakes the database before the event." },
  "landing.codeInvalid": { m: "The event code box got something that is not an event address.", f: "Type the last part of the event's address, for example arrow-launch-2026." },
  // ---- join
  "join.errors.INVALID_PIN": { m: "The event code or the 6-digit PIN does not match an active seat.", f: "Check the event code (the last part of the event address) and the PIN on the card. The organiser sees every PIN in Officials → Show PIN, or makes a new one with Regenerate PIN." },
  "join.errors.INVALID_TOKEN": { m: "A QR card works once; printing the cards again makes the older QR codes stop working.", f: "Type the PIN instead, or print a fresh card (Officials → Print card)." },
  "join.errors.RATE_LIMITED": { m: "Too many wrong PINs from this connection.", f: "Wait ten minutes, or let the organiser read the PIN out from Officials → Show PIN." },
  "join.errors.SEAT_LOCKED": { m: "The seat is held by another phone.", f: "Organiser: Officials → Regenerate PIN for the seat (signs the old phone out), then join with the new PIN." },
  "join.errors.NO_SESSION": { m: "The phone could not start its anonymous session (no signal, or private mode blocks storage).", f: "Check the connection; on iPhone join from the home-screen app, not a private tab." },
  "join.errors.ORGANISER_SESSION": { m: "This browser is signed in as an organiser; a seat needs its own session.", f: "Use another browser or a private window to join as an official." },
  "join.otherError": { m: "An unexpected answer from the server.", f: RETRY },
  "join.selfAdd.errors.EVENT_NOT_FOUND": { m: "The event is not published or not taking requests." },
  "join.selfAdd.errors.TOO_MANY_PENDING": { m: "Many requests are already waiting for approval.", f: "Organiser: Officials → Waiting for approval → approve or decline." },
  "join.selfAdd.failed": { m: "The request did not reach the server.", f: RETRY },
  // ---- login
  "login.linkFailed": { m: "The sign-in link expired, was used already, or was opened in a different browser from the one that asked for it.", f: "Ask for a new link and open it on the same phone or computer, in the same browser." },
  "login.linkExpired": { m: "Each sign-in link works once, for 24 hours; this one was used or is older.", f: "Ask for a new one with “Forgot password?” (once a password is set) or ask the platform owner to send another invitation." },
  "login.notRegistered": { m: "Sign-in is invite-only: this email has no organiser login.", f: "The platform owner invites the address (Admin → organisation → Invite organiser)." },
  "login.tooMany": { m: "The hosted email service sends only a few sign-in emails per hour.", f: "Wait up to an hour, or sign in with a password (set one once from the account menu → Set or change password)." },
  "login.couldNotSend": { m: "The email service refused or could not be reached." },
  "login.wrongPassword": { m: "The email and password do not match.", f: "Check them, or use “Sign in with a link instead”." },
  "login.notAnOrganiser": { m: "The login exists but belongs to no organisation.", f: "The platform owner adds it to an organisation." },
  "setPassword.couldNotSave": { m: "The sign-in session is too old to change the password.", f: "Sign in with a link again, then set the password." },
  // ---- seat
  "seat.switchedOff": { m: "The organiser switched this seat off in the Officials step.", f: "Organiser: Officials → the seat → Switch on." },
  "seat.noSeat": { m: "This phone has not joined yet, or its seat was regenerated.", f: "Join with the PIN." },
  // ---- event lifecycle
  "eventLifecycle.deleteBlocked": { m: "Published results are permanent.", f: "Archive the event instead (hidden everywhere, nothing deleted)." },
  "eventLifecycle.ownerOnly": { m: "Delete and archive are platform-owner actions." },
  "eventLifecycle.errors.SLUG_MISMATCH": { f: "Type the event's web address exactly as shown under the box." },
  // ---- org settings
  "orgSettings.readOnly": { m: "Your role in this organisation is not owner or admin." },
  "orgSettings.readOnlyReason": { m: "Your role in this organisation is not owner or admin.", f: "Ask an owner of the organisation, or the platform owner." },
  "orgSettings.understandFirst": { m: "Changing the address breaks links and printed QR codes already out.", f: "Tick “I understand, change the address”, then Save." },
  "orgSettings.slugTaken": { f: "Choose another web address." },
  // ---- logo
  "logo.uploadFailed": { m: "The upload did not reach storage.", f: "Check the connection and choose the file again." },
  // ---- readiness
  "readiness.pinHint": { m: "A seat made before PINs were stored has no PIN the screen can show; its phone still joins with the PIN it was given." },
  // ---- event step
  "event.understandFirst": { m: "The event is published; changing its address breaks shared links and QR codes.", f: "Tick “I understand, change the address”, then Save event." },
  "event.sponsorFirst": { m: "The ↑ button is grey because this sponsor is at the top.", f: "Nothing to fix." },
  "event.sponsorLast": { m: "The ↓ button is grey because this sponsor is at the bottom.", f: "Nothing to fix." },
  "event.simulationLocked": { m: "“Simulation event” can be switched only before any heat of the event has started.", f: "Use Run as simulation on the Simulator page to rehearse a real event instead." },
  "event.notFound": { m: "The event does not exist, or this login is not in its organisation.", f: "Pick the organisation in the switcher at the top, then open the event from the events list." },
  "event.slugTaken": { f: "Choose another web address (slug)." },
  "event.saveDenied": { m: "This login may not change the event (another organisation, or no membership)." },
  "event.saveFailed": { f: RETRY },
  "event.validation.closesAfterEnd": { f: "Set the closing day on or before the event's last day." },
  "event.validation.timeZone": { f: "Pick a time zone from the list, for example Africa/Cairo." },
  // ---- ident
  "ident.validation.namesUnique": { m: "The spotter calls colours out by name, so two colours with one name could not be told apart." },
  "ident.validation.fallbackDiffers": { f: "Choose a different fallback, or No fallback." },
  // ---- divisions
  "divisions.firstDivision": { m: "The ↑ button is grey: this division is already first.", f: "Nothing to fix." },
  "divisions.lastDivision": { m: "The ↓ button is grey: this division is already last.", f: "Nothing to fix." },
  "divisions.hasHeats": { m: "A division with heats (a draw was made) cannot be deleted: it would delete the draw and any results.", f: "Keep it, or rename it. To start the division again use Reset this division." },
  "divisions.errors.hasHeats": { m: "A division with heats cannot be deleted.", f: "Keep it, or use Reset this division." },
  "divisions.identification.switchOff": { f: "Event step → Rider identification → tick “Allow a different scheme for individual divisions”, Save event, then come back." },
  "divisions.identification.ownKeptButOff": { m: "The division's own scheme is kept but not used while the event's switch is off." },
  "divisions.identification.errors.locked": { m: "Once a heat of the division has started, the Rider label is fixed so every screen keeps showing riders the same way." },
  "divisions.errors.rulesLocked": { m: "Scoring and format lock at the first heat of the division so results already entered keep their meaning.", f: "Divisions → the division → “Unlock scoring and format” with a reason of at least 5 characters (written to the audit log)." },
  "divisions.errors.reason": { f: "Write at least 5 characters, for example “wind dropped, shorter heats”." },
  "divisions.errors.onlyOwn": { m: "Built-in presets never change.", f: "Use “Save as new preset”." },
  "divisions.errors.notValidTogether": { f: "Read the list of problems above the Save button and fix each one." },
  // ---- rules
  "rules.loadLocked": { m: "The Load… menu is grey because the rules are locked (a heat has started).", f: "Unlock scoring and format with a reason first." },
  "rules.unlockNeedsReason": { m: "The Unlock button is grey until a reason is typed." },
  "rules.saveInvalid": { m: "The Save button is grey while a setting has a problem." },
  // ---- format
  "formatSimple.perRound.empty": { f: "Change the number in “Preview with” or the ladder settings until the preview shows rounds." },
  "formatSimple.finalEven": { m: "Double elimination takes the same number of riders from the main and second-chance draws into the final." },
  "customBuilder.lastRound": { m: "A ladder should end in a single final heat." },
  "ladder.cannotRun": { m: "The format's numbers do not fit this field size (too few riders, or nobody would be knocked out)." },
  // ---- draw
  "draw.noFormat": { m: "Generate draw is grey: the division has no format yet.", f: "Divisions → the division → Format tab → choose a format → Save format." },
  "draw.noRiders": { m: "Generate draw is grey: no rider of the division is Confirmed.", f: "Riders step → set riders to Confirmed (or approve registrations)." },
  "draw.unlockReasonShort": { m: "Unlock is grey until the reason has at least 5 characters." },
  "draw.regenerateRefusedStarted": { m: "Once a heat of the division has started, the draw can no longer be made again.", f: "Change single seats by hand, or Reset this division (Divisions step) to start the division over." },
  "draw.regenerateRefusedLocked": { m: "A locked draw cannot be regenerated.", f: "Unlock draw (with a reason), regenerate, lock again." },
  "draw.startedNote": { m: "Heats that started or finished are fixed; later heats can still be changed by hand." },
  "draw.lockedHelp": { m: "Locked: seats, heats and rounds are frozen; heats can start.", f: "Unlock draw with a reason only if you must change it." },
  "draw.droppedNote": { m: "Regenerating kept your hand-arranged heats where they still fit; these did not." },
  "draw.sheet.pngFailed": { m: "The browser could not make the picture.", f: "Use Print / PDF and choose “Save as PDF”." },
  "draw.errors.locked": { f: "Unlock draw (with a reason), change it, lock again." },
  "draw.errors.started": { m: "A started or finished heat cannot change." },
  "draw.errors.badFormat": { f: "Divisions → Format tab: fix the format until its preview shows a ladder for this number of riders." },
  // ---- builder
  "builder.applyBlocked": { m: "Apply to draw is grey while the checker shows red points." },
  "builder.applyNoRiders": { m: "Apply to draw is grey: no rider is Confirmed." },
  "builder.drawLocked": { f: "Draw step → Unlock draw with a reason, then apply." },
  "builder.drawStarted": { m: "A heat has started, so the whole draw cannot be replaced.", f: "Change seats in the Draw step, or Reset this division first." },
  // ---- run order
  "runOrder.noHeats": { m: "The Run order lists heats from the draws; no division has a draw yet.", f: "Draw step → Generate draw for each division." },
  "runOrder.goneHeat": { m: "A run-order row points at a heat that a later re-draw removed. It takes no time and is never “next”.", f: "Take the row out with ✕ (or Take row out of the run order), then Add the heats that are missing." },
  "runOrder.errors.twoActive": { f: "Activate the plan you want; the other active plan of that day is switched off by Activate this plan." },
  "runOrder.errors.deleteActive": { f: "Activate another plan of that day first, then delete this one." },
  "runOrder.errors.unknownHeat": { m: "The plan names a heat that is not in this event (it was removed by a re-draw).", f: "Take the row out and add the heat again." },
  // ---- presets import
  "presets.wrongKind": { f: "Import a scoring file in the Scoring tab and a format file in the Format tab." },
  // ---- admin
  "admin.errors.PUBLISHED_RESULTS": { f: "Archive the organisation instead." },
  "admin.errors.HEAT_RUNNING": { f: "End the running heat, then move the event." },
  "admin.errors.PRESETS_MISSING": { f: "On a computer with the keys: npm run seed:presets." },
  "admin.org.inviteEmailFailed.rate_limit": { m: "The hosted e-mail plan sends only 2 sign-in e-mails per hour and they are used up; the login was still made.", f: "Copy the sign-in link shown and send it privately (WhatsApp); it works once, for 24 hours. Or invite again after an hour." },
  "admin.org.inviteEmailFailed.not_authorised": { m: "The built-in e-mail sender of the hosted plan only writes to the project team's own addresses; the login was still made.", f: "Copy the sign-in link shown and send it privately. A custom e-mail sender (SMTP) removes this limit." },
  "admin.org.inviteEmailFailed.other": { m: "The e-mail service refused; the login was still made.", f: "Copy the sign-in link shown and send it privately." },
  "admin.org.removeSelf": { m: "Remove is grey on your own login.", f: "Another platform owner can remove it." },
  "admin.errors.NOT_A_MEMBER": { m: "The person was already removed from this organisation (or never was a member).", f: "Reload the organisation page." },
  "admin.errors.CANNOT_REMOVE_SELF": { m: "A platform owner cannot remove their own login from an organisation." },
  "admin.org.logoFailed": { f: "Upload the logo again on the organisation's page." },
  "admin.crash.heading": { m: "An admin page failed on the server.", f: "Press Try again; open Health to check the server settings; search the hosting logs for the error reference." },
  "admin.partProblem": { m: "One part of the page could not be read; the rest works." },
  "admin.demo.drawFailed": { f: "On a computer with the keys: npm run seed:demo." },
  "admin.presets.errors.NOT_NEWER": { f: "Save the content as a new version; that version can be published." },
  "admin.health.databaseDown": { m: "The server cannot reach the database (free projects pause after about 7 days idle).", f: "Open the Supabase dashboard and press Resume; load the home page once." },
  "admin.health.realtimeOff": { m: "The browser could not open a live connection. Phones fall back to asking every few seconds.", f: "Reload; check the hotspot. Not blocking: screens still update by polling." },
  "admin.health.settingsUnreadable": { m: "The platform settings could not be read, so the built-in name and texts are shown." },
  // ---- riders
  "riders.noDivisions": { f: "Divisions step → + Add division." },
  "riders.needTwo": { m: "Shuffle and Sort are grey with fewer than two riders." },
  "riders.firstRow": { m: "↑ is grey: the rider is already first.", f: "Nothing to fix." },
  "riders.lastRow": { m: "↓ is grey: the rider is already last.", f: "Nothing to fix." },
  "riders.nameRequiredHint": { m: "+ Add rider is grey until both names are typed." },
  "riders.seedRepeated": { f: "Press “Sort by seed number” to renumber 1, 2, 3…" },
  "riders.inDraw": { m: "Removing a rider who has a seat would leave an empty seat in the draw.", f: "Set the rider to Withdrawn." },
  "riders.drawLocked": { m: "The draw keeps the order it was made with; seeds changed now do not move riders.", f: "To use new seeds: Draw step → Unlock (reason) → Regenerate → Lock (only before the first heat)." },
  "riders.clash.lycra": { m: "A warning: two riders share a Lycra colour, so judges could not tell them apart. Nothing is blocked." },
  "riders.clash.name": { m: "A warning: two riders share a name, so the spotter could not call them out apart. Nothing is blocked.", f: "Add a nickname or a bib number." },
  "riders.importFailed": { m: "The import stopped; nothing was half-saved.", f: RETRY },
  "riders.errors.emailUsed": { f: "Use the rider who already has that email (Add from this organisation’s riders)." },
  // ---- trick base
  "trickBase.lockedNote": { m: "After the first heat of a division, ticked blocks stay ticked so the spotter's screen does not lose a trick mid-event." },
  "trickBase.cannotUntick": { m: "The box is grey: a heat has started." },
  "trickBase.errors.noVocabulary": { f: "On a computer with the keys: npm run seed:presets." },
  // ---- feedback
  "feedback.exportOwnerOnly": { m: "Only the platform owner exports notes." },
  // ---- officials
  "officials.shortfall": { m: "The panel has fewer judges than the division's scoring rules ask for. A warning: heats can start only when the panel is big enough (the head console refuses with PANEL_TOO_SMALL).", f: "Officials → Panels: tick more judges for the division, or lower “Number of judges” in Divisions → Scoring." },
  "officials.pinUnknown": { m: "The seat was made before PINs were stored; the phone already joined still works.", f: "Regenerate PIN (the old PIN stops working and the seat's phones are signed out)." },
  "officials.pinCouldNotRead": { f: "Regenerate PIN." },
  "officials.printNone": { m: "Print cards is grey: no active seat." },
  "officials.printNoPin": { f: "Regenerate PIN for that seat, then print." },
  "officials.inHeat": { m: "Regenerate PIN and some seat changes are off while the seat's heat is running, so a judge is not signed out mid-heat.", f: "Wait until the heat ends." },
  "officials.panelsNoJudges": { f: "Add a seat with role Judge first." },
  "officials.errors.noKey": { m: "The server is missing the key that protects PINs.", f: "Owner: Admin → Health → Server settings; set SUPABASE_SERVICE_ROLE_KEY (or SEAT_PIN_KEY) on the host and redeploy." },
  "officials.errors.hasScores": { m: "Scores already given keep the seat.", f: "Switch the seat off instead." },
  "officials.errors.pinInUse": { f: "Press again: a new random PIN is tried." },
  // ---- registration
  "registration.closedDefault": { m: "Registration is switched off, past its closing time, or the event is not published.", f: "Organiser: Event step → Rider registration → Open, closing day in the future; Published ticked." },
  "registration.fullLine": { m: "The division reached “Most riders per division”.", f: "Organiser: raise the number in the Event step, or add the rider by hand in Riders." },
  "registration.photoFailed": { f: "Register without the photo and send it to the organiser." },
  // ---- live phones
  "live.connection.failed": { m: "A score or attempt failed to send after retries.", f: "Tap the badge to retry. If it still fails, read the sentence; the head judge can type the score on the console." },
  "live.queue.memoryOnly": { m: "The phone's browser does not keep unsent scores through a reload (private mode or storage blocked).", f: "Keep the page open until Synced; on iPhone use the home-screen app." },
  "live.builder.micDenied": { f: "Allow the microphone in the phone's settings, or type the trick." },
  "live.impression.submitWaiting": { m: "Submit is grey until every rider has an Impression / Variety score." },
  "live.impression.submitted": { m: "The sheet is submitted and locked.", f: "Head judge: console → judge's row → reopen the sheet." },
  "judge.locked": { m: "The judge submitted the sheet; scores are locked.", f: "Head judge reopens the sheet, or edits the score with a reason on the console." },
  "judge.reviewLocked": { m: "The heat is under review; judges' scores are locked.", f: "Tell the head judge the correction; they edit it on the console with a reason." },
  "judge.notOnPanel": { m: "The running heat's division does not have this judge on its panel.", f: "Organiser: Officials → Panels → tick the judge for that division." },
  "judge.stillSending": { f: "Wait for Synced (check signal), then Submit." },
  "spotter.paused": { m: "The head judge paused the heat." },
  "spotter.notRunning": { m: "The heat has not started, ended, or time is up." },
  "spotter.outOfAttempts": { m: "The rider used the division's attempt cap. Their Rider label is grey.", f: "Only the head judge can add one more, with a reason (console → Add attempt)." },
  "spotter.refusedCap": { m: "The server refused an attempt past the cap (two phones raced, or the phone was stale).", f: "Head judge adds it with a reason if it really happened." },
  "spotter.refusedOther": { m: "The server refused the attempt; the reason follows the colon." },
  "spotter.undoFailed": { m: "Undo works for 10 seconds after logging.", f: "Ask the head judge to delete the attempt." },
  // ---- simulator
  "simulator.needLock": { f: "Draw step → Lock draw for each division (of the simulation copy)." },
  "simulator.notSimulation.notDrawn": { f: "Open the copy's Draw step and lock each division's draw before Start." },
  "simulator.play.lines.waitHead": { m: "The head judge seat is set to Real or held by a person, so the simulator waits.", f: "Publish on the head console, or set the head judge to Virtual." },
  "simulator.play.lines.waitJudges": { m: "A judge seat set to Real has not submitted.", f: "Submit on that phone, or set the judge to Virtual." },
  "simulator.play.lines.hold": { f: "Resume the run order (Go live → Resume at…, or the scenario button again)." },
  "simulator.play.lines.notReady": { f: "Lock the division's draw; finish the earlier heats that fill this heat's seats." },
  "simulator.play.lines.busy": { m: "Auto-play runs in one tab at a time.", f: "Close the other tab, or use it." },
  "simulator.log.noCap": { f: "Divisions → Scoring → set “Attempts per rider”." },
  "simulator.needTyped": { m: "The Reset or Delete button is grey until the event's web address is typed.", f: "Type the address shown under the box." },
  "simulator.reset.noBaseline": { m: "No copy of the locked draw was saved (the Demo was played before Reset existed).", f: "Use “Wipe and draw again”." },
  "simulator.errors.NOT_A_COPY": { m: "Delete is only for copies made with Run as simulation." },
  "simulator.errors.SOURCE_ALREADY_RUN": { f: "Copy the event before its first heat, or reset it first." },
  "simulator.errors.NO_KEY": { f: "Owner: set SUPABASE_SERVICE_ROLE_KEY (or SEAT_PIN_KEY) on the host." },
  // ---- wind
  "windCall.bannerOffNote": { m: "The call is saved but not shown: the banner switch is off.", f: "Event step → tick “Show the wind-call banner…”." },
  // ---- live database codes
  "liveErrors.network": { m: "The phone has no connection. The action waits in the phone's queue and is sent when the connection is back (no duplicates).", f: "Keep the page open; move toward the hotspot." },
  "liveErrors.unknown": { m: "An answer the screen does not know.", f: RETRY },
  "liveErrors.codes.NOT_ALLOWED": { m: "This login or seat may not do this (wrong role, another event, or the seat was switched off)." },
  "liveErrors.codes.HEAT_TIME_UP": { m: "The heat's clock reached zero; the server treats it as ended." },
  "liveErrors.codes.HEAT_PUBLISHED": { m: "A published heat cannot change.", f: "Head judge: Re-open, correct, Publish again (a new version)." },
  "liveErrors.codes.ILLEGAL_HEAT_TRANSITION": { m: "For example Pause on a heat that is not running.", f: "Reload; the buttons show what the heat can do now." },
  "liveErrors.codes.USE_HEAT_FUNCTIONS": { m: "A heat's state changes only through Start / Pause / Resume / End / Publish." },
  "liveErrors.codes.DRAW_NOT_LOCKED": { m: "A heat can start only when its division's draw is locked.", f: "Draw step → Lock draw." },
  "liveErrors.codes.PANEL_TOO_SMALL": { m: "Fewer judges are on the division's panel than its scoring rules need.", f: "Officials → Panels: tick more judges, or lower “Number of judges” in Divisions → Scoring." },
  "liveErrors.codes.SEATS_NOT_FILLED": { m: "A seat still shows a placeholder such as “1st H1”: the heat that feeds it is not published.", f: "Publish the earlier heat, or place a rider in the seat in the Draw step." },
  "liveErrors.codes.HEAT_ALREADY_RUNNING": { m: "The event allows only this many heats running (or paused) at once.", f: "End the other heat, or raise “Heats that can run at the same time” in the Event step." },
  "liveErrors.codes.REASON_REQUIRED": { f: "Type a reason; it is written to the audit log." },
  "liveErrors.codes.OVERRIDE_REASON_REQUIRED": { f: "Type a reason; it is written to the audit log." },
  "liveErrors.codes.PLAN_NOT_ACTIVE": { f: "Run order step → Activate this plan." },
  "liveErrors.codes.PLAN_CHANGED": { m: "Two people changed the run order at the same moment.", f: "Press again." },
  "liveErrors.codes.NOTHING_TO_SHIFT": { m: "Shift moves only heats that have not started." },
  "liveErrors.codes.NOT_ON_HOLD": { m: "Resume at works only while the run order is on hold." },
  "liveErrors.codes.ON_HOLD": { f: "Use Resume at (pick the restart time)." },
  "liveErrors.codes.NO_ACTIVE_PLAN": { f: "Run order step → pick today → Activate this plan." },
  "liveErrors.codes.ATTEMPT_CAP_REACHED": { m: "The rider used every attempt the division allows.", f: "Only the head judge adds one more, with a reason." },
  "liveErrors.codes.PUBLISH_BLOCKED": { f: "Read “Before you publish”; fix each line, or Publish with a reason (ties must be ordered, never overridden)." },
  "liveErrors.codes.SHEETS_NOT_SUBMITTED": { f: "Wait for the judges' Submit, or Publish with a reason." },
  "liveErrors.codes.VERSION_CONFLICT": { m: "Someone published or re-opened the heat at the same moment.", f: "Look at the heat again, then act." },
  "liveErrors.codes.HEAT_NOT_ENDED": { f: "Press End heat first." },
  "liveErrors.codes.HEAT_CANCELLED": { f: "Re-run the heat instead (head console)." },
  "liveErrors.codes.HEAT_ALREADY_RERUN": { m: "A cancelled heat can be re-run once.", f: "Work on the re-run heat (for example H1R)." },
  "liveErrors.codes.NOT_ON_PANEL": { f: "Officials → Panels: tick the judge for the division." },
  "liveErrors.codes.SCORE_OFF_STEP": { m: "The scale's step (for example 0.5) does not allow this value." },
  "liveErrors.codes.NO_IMPRESSION": { m: "The division's scoring rules have no Impression / Variety score." },
  "liveErrors.codes.FLAG_OUT_NOT_AVAILABLE": { m: "The format has no flag-out for this round." },
  "liveErrors.codes.HEAT_NOT_STARTED": { f: "Press Start heat." },
  "liveErrors.codes.NOT_A_SIMULATION": { m: "The Practice heat feed plays only on a simulation event.", f: "Use Run as simulation, or tick Simulation event before any heat starts." },
  "liveErrors.codes.SIMULATION_LOCKED": { m: "“Simulation event” can be changed only before the first heat starts." },
  "liveErrors.codes.DOWNSTREAM_STARTED": { m: "The result already filled a seat of a heat that has started; changing it now would change who rode.", f: "Reset or finish the later heat first, or leave the result." },
  "liveErrors.codes.DRAW_MISMATCH": { m: "The stored draw and this heat disagree (it was changed elsewhere).", f: "Reload the page; if it repeats, tell the owner." },
  "liveErrors.codes.RIDER_NOT_RIDING": { m: "The rider is DNS or flagged out." },
  "liveErrors.codes.CLIENT_KEY_REUSED": { m: "A queued tap from an earlier heat was sent again.", f: "Reload the page." },
  "liveErrors.codes.UNDO_TOO_LATE": { m: "Undo works for 10 seconds after logging." },
  "liveErrors.codes.SHEET_LOCKED": { f: "Head judge reopens the sheet." },
  "liveErrors.codes.IMPRESSION_MISSING": { f: "Give each rider an Impression / Variety score, then Submit." },
  "liveErrors.codes.IMPRESSION_NOT_OPEN": { f: "Wait for the head judge to end the heat." },
  "liveErrors.codes.NOT_SCORABLE": { m: "A crashed attempt has nothing to score." },
  // ---- crash pages
  "crash.heading": { f: "Press Try again; use the link back. Send the error reference to the owner if it repeats." },
  "crash.part": { m: "One part of the page failed (for example the run-order list); the rest of the page works." },
  // ---- head console
  "heatControl.noPlan": { m: "The console lists heats by division because no run order is active for today." },
  "headV2.notNext": { m: "You pressed Start on a heat that is not next in the active run order.", f: "Start anyway (the timetable re-flows) or Don’t start." },
  "headV2.breakNone.no-plan": { f: "Run order step → Activate this plan for today." },
  "headV2.breakNone.no-time": { f: "Run order step → pin a start time on the first row." },
  "publish.noModel": { f: "Divisions → the division → Scoring tab → choose a preset → Save." },
  "publish.downstream": { m: "Re-publishing would change who rides in a later heat that has already started.", f: "Leave the result, or reset the later heat first." },
  "headLive.publishNoOverride": { f: "Press Choose order and set the order of the tied riders." },
  "headLive.flagOutUndecided": { f: "Tick the rider to flag out." },
  "headLive.pastCapNotAllowed": { m: "An organiser or head judge seat is needed to add an attempt past the cap." },
  "headLive.practiceNoHeat": { f: "Start a heat, then Start the practice feed." },
  // ---- resets
  "reset.blocked": { m: "The list under it names what stops the reset (for example a division to unlock and lock again)." },
  "reset.needAddress": { m: "The confirm button is grey until the event's web address is typed exactly." },
  "reset.needReason": { m: "The confirm button is grey: results were public, so a reason is needed." },
  "reset.errors.HEAT_RUNNING": { f: "End the heat on the head console, then reset." },
  "reset.errors.DRAW_COPY_MISSING": { m: "A division has no saved starting copy (locked before Reset existed)." },
  "reset.restore.errors.HEAT_STARTED": { m: "Restoring would mix with heats run after the reset." },
  "reset.rebuildArranged": { m: "A later round has hand-placed seats, so its starting draw cannot be rebuilt." },
  "reset.copyRelock": { f: "Draw step → Unlock draw (reason) → Lock draw, while no heat of the division has started." },
  "reset.copyUnknown": { f: "Reset this division (it rebuilds from the current draw), or leave it." },
  "resetParts.alreadyRerunAs": { m: "Re-run is grey: the cancelled heat already has its re-run (named here).", f: "Work on the re-run heat." },
  "resetParts.errors.HEAT_ALREADY_RERUN": { f: "Reset the re-run heat instead." },
  "resetParts.errors.DOWNSTREAM_STARTED": { f: "Reset the later heat first, then this one." },
  "resetParts.plan.nothing": { m: "Clear actual times is grey: nothing was written while the day ran." },
  "resetParts.heat.scheduledWhy": { m: "Reset this heat is grey: the heat never started." },
  "resetParts.division.noHeats": { m: "Reset this division is grey: the division has no heats." },
  // ---- grey buttons (head console)
  "controlWhy.noPlan": { m: "Hold, Resume at and Shift are grey: no run order is active for today.", f: "Run order step → pick today → Activate this plan." },
  "controlWhy.start": { m: "Start heat is grey: the selected heat has started already.", f: "Pick the next heat in the run order." },
  "controlWhy.startCancelled": { m: "Start heat is grey on a cancelled heat.", f: "Heat menu → Re-run heat." },
  "controlWhy.rerunDone": { m: "Re-run is grey: done once already." },
  "controlWhy.pause": { m: "Pause is grey: the heat is not running." },
  "controlWhy.resume": { m: "Resume is grey: the heat is not paused." },
  "controlWhy.end": { m: "End heat is grey: the heat is not running or paused." },
  "controlWhy.live": { m: "The live-scores switch works only during a heat." },
  "controlWhy.cancel": { m: "Cancel heat is grey before the heat starts or after it is published." },
  "controlWhy.rerunPublished": { m: "Re-run is grey on a published heat.", f: "Re-open the heat, correct it, Publish again." },
  "controlWhy.publish": { m: "Publish is grey until the heat has ended.", f: "Press End heat (or wait for the clock)." },
  "controlWhy.reopen": { m: "Re-open is grey: the heat is not published." },
  "controlWhy.blockers": { m: "Publish is grey: the listed things block it.", f: "Open Details (phone) or read “Before you publish” (laptop); fix them or Publish with a reason." },
  // ---- go live quick actions
  "org:dashboard.alreadyHeld": { m: "Hold is grey: the run order is already on hold." },
  "org:dashboard.notHeld": { m: "Resume at… is grey: nothing is on hold." },
  "org:dashboard.noPlanToday": { m: "Hold, Resume at… and Shift are grey: no run order is active for today in the event's time zone.", f: "Run order step → choose today's day → Activate this plan. If the plan is for another day, the Go live checklist names both days." },
  "org:dashboard.shiftHeld": { m: "Shift is grey while on hold.", f: "Resume at… first, or use Resume at to set the restart time." },
  "org:dashboard.failed": { m: "The server refused the quick action; the reason follows the colon." },
  "org:dashboard.resetRefused": { f: "End the heat (head console), then Reset event…" },
};

/** Database codes that have no sentence of their own: what the screen shows instead. */
export const CODES_WITHOUT_SENTENCE: Record<string, { shown: string; meaning: string }> = {
  APPEND_ONLY: { shown: "the screen's general “That did not work” sentence", meaning: "Published results and the audit log can never be edited or deleted; only Re-open and Publish again add a new version." },
  BAD_ACTION: { shown: "“That did not work. Nothing was changed.” (Draw step)", meaning: "The Draw step sent an unknown kind of change. A bug: tell the owner." },
  BAD_ENTRY: { shown: "“That did not work. Nothing was changed.” (Draw step)", meaning: "A seat names a rider who is not in the division." },
  DIVISION_HAS_HEATS: { shown: "“This division already has heats, so it cannot be deleted.”", meaning: "Deleting a division with heats is refused." },
  DRAW_FUNCTION_ONLY: { shown: "the Draw step's general sentence", meaning: "The draw and its lock change only through the Draw step's buttons." },
  DRAW_LOCKED: { shown: "“The draw is locked. Unlock it (with a reason) to change it.”", meaning: "A seat of a locked draw cannot be moved." },
  INVALID_JSON: { shown: "“The settings could not be saved…” (Platform settings)", meaning: "A platform setting was not valid." },
  INVALID_KEY: { shown: "“The settings could not be saved…” (Platform settings)", meaning: "An unknown platform setting." },
  INVALID_KIND: { shown: "“That did not work…” (Master presets)", meaning: "An unknown kind of preset." },
  INVALID_ORDER: { shown: "“That did not work. Nothing was changed; try again.” (Riders)", meaning: "The new rider order did not list every rider of the division once." },
  INVALID_ROWS: { shown: "“The import did not finish. Nothing was half-saved; try again.”", meaning: "The rider file reached the server in a shape it does not accept." },
  INVALID_SEATS: { shown: "“That did not work…” (Officials)", meaning: "“Head judge also scores” was set on a seat that is not a head judge." },
  INVALID_SETTINGS: { shown: "“The settings could not be saved…” (Organisation settings)", meaning: "An organisation setting was not valid (for example the time zone)." },
  INVALID_STATUS: { shown: "“That did not work…” (Trick proposals)", meaning: "An unknown proposal status." },
  NO_BASELINE: { shown: "“This event has no saved locked draw to go back to…” (Simulator)", meaning: "The simulation has no saved starting draw." },
  NOT_SIGNED_IN: { shown: "nothing (the seat's “last seen” is not updated)", meaning: "A phone without a session tried to report that it is alive." },
  PIN_IN_USE: { shown: "“Could not find a free PIN; try again.”", meaning: "The random PIN was already taken; the screen tries again." },
  PIN_MUST_BE_6_DIGITS: { shown: "“That did not work…” (Officials)", meaning: "A PIN must be six digits." },
  RIDER_OTHER_ORGANISATION: { shown: "“That did not work…” (Riders)", meaning: "A rider of another organisation cannot be entered." },
  RULES_LOCKED: { shown: "“Scoring and format are locked because a heat of this division has started…”", meaning: "The division's rules lock at its first heat." },
  TOO_MANY_ROWS: { shown: "“The file has more than ‹n› riders…”", meaning: "The rider file is too long." },
  TRICK_BASE_INVALID: { shown: "“That did not work…” (Trick base)", meaning: "The trick base sent was not in the expected shape." },
  TRICK_BASE_LOCKED: { shown: "“A heat has started, so blocks cannot be removed.”", meaning: "A ticked block cannot be unticked after the division's first heat." },
  VOCABULARY_OTHER_ORGANISATION: { shown: "“That did not work…” (Trick base)", meaning: "A trick block belongs to another organisation's event." },
};
