// Writes supabase/combined.sql: every migration in order (plus the demo seed with --seed), for pasting
// into the Supabase SQL Editor when the API route is unavailable.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const withSeed = process.argv.includes("--seed");
const files = readdirSync("supabase/migrations").filter((f) => f.endsWith(".sql")).sort();
let out = "-- GENERATED by `npm run db:combine`. Do not edit. Paste into Supabase > SQL Editor > New query > Run.\n-- Safe to run once on an empty project.\n";
for (const f of files) out += `\n-- ===== migration ${f} =====\n${readFileSync(`supabase/migrations/${f}`, "utf8")}\n`;
if (withSeed) out += `\n-- ===== seed.sql (demo data; run seed:presets first) =====\n${readFileSync("supabase/seed.sql", "utf8")}\n`;
writeFileSync("supabase/combined.sql", out);
console.log(`Wrote supabase/combined.sql (${files.length} migrations${withSeed ? " + seed" : ""}).`);
