import type { LabelMap } from "./nodes";

/** Plain-language labels for the scoring model (docs/03 §3). A test fails when a schema field has no entry here. */
export const SCORING_HIDDEN = ["id", "version", "basedOn"] as const;

export const SCORING_LABELS: LabelMap = {
  name: { label: "Name" },
  description: { label: "Description", help: "Shown to organisers when choosing a scoring model." },

  trick: { label: "Trick scoring" },
  "trick.entry": {
    label: "What judges enter for each trick",
    help: "Criteria: several marks that are combined. Single: one mark. None: judges do not score tricks.",
    values: { criteria: "Several criteria (height, extremity, …)", single: "One mark per trick", none: "Nothing (overall score only)" },
  },
  "trick.scale": { label: "Trick score scale", help: "The range of the trick score after combining." },
  "trick.scale.min": { label: "Lowest" },
  "trick.scale.max": { label: "Highest" },
  "trick.scale.step": { label: "Step", help: "The smallest jump on the score pad, e.g. 0.1 or 0.5." },
  "trick.criteria": { label: "Criteria", help: "What judges mark for each trick. Order is the order on the score pad." },
  "trick.criteria.*": { label: "Criterion" },
  "trick.criteria.*.key": { label: "Short code", help: "Lowercase letters, numbers and _, e.g. height. Must be unique." },
  "trick.criteria.*.label": { label: "Name shown to judges" },
  "trick.criteria.*.help": { label: "Hint for judges", help: "One line shown behind the “?” button." },
  "trick.criteria.*.scale": { label: "Scale" },
  "trick.criteria.*.scale.min": { label: "Lowest" },
  "trick.criteria.*.scale.max": { label: "Highest" },
  "trick.criteria.*.scale.step": { label: "Step" },
  "trick.criteria.*.weight": { label: "Weight", help: "How much this criterion counts when the marks are combined." },
  "trick.criteria.*.sensorFill": { label: "Filled by the height sensor", values: { height: "Height" } },
  "trick.combine": {
    label: "How criteria are combined",
    values: { weighted_mean: "Weighted average, scaled to the trick scale", sum: "Add them up (maximums must add up to the trick scale)" },
  },
  "trick.crash": { label: "A crashed attempt", values: { not_counted: "Is not counted", zero: "Counts as 0" } },
  "trick.allowNoScore": { label: "Judges may mark “Missed” (did not see it)" },

  panel: { label: "Judge panel" },
  "panel.minJudges": { label: "Fewest judges", help: "The panel size the rules are designed for. The app warns below 3." },
  "panel.maxJudges": { label: "Most judges" },
  "panel.aggregate": { label: "How the judges’ marks are combined", values: { mean: "Average (mean)", trimmed_mean: "Trimmed average (drop highest and lowest)", median: "Median (middle mark)" } },
  "panel.trimMinJudges": { label: "Trim only with at least this many judges", help: "Below this the plain average is used." },
  "panel.decimals": { label: "Decimal places for scores and totals" },
  "panel.outlierWarnPct": { label: "Warn the head judge when two judges differ by more than (% of the scale)" },
  "panel.requireAllJudges": { label: "Every judge must mark before publishing", help: "The head judge can still override with a written reason." },

  heat: { label: "Counting and heat total" },
  "heat.counting": { label: "Which tricks count", help: "Choose the rule, then fill in its details." },
  "heat.counting=best_n": { label: "Best N tricks" },
  "heat.counting=best_per_category": { label: "Best tricks per category" },
  "heat.counting=single_best": { label: "Single best trick" },
  "heat.counting=all": { label: "All tricks" },
  "heat.counting=none": { label: "No tricks (overall score only)" },
  "heat.counting.n": { label: "Number of tricks that count" },
  "heat.counting.distinctTrickNames": { label: "Each trick name counts only once", help: "Only the best of identically named tricks counts." },
  "heat.counting.maxPerCategory": { label: "Tricks per category that count", help: "Applies to every category not listed below." },
  "heat.counting.perCategoryMax": { label: "Different limit for some categories", help: "For example kiteloop: 2 lets two kiteloops count while other categories keep the limit above." },
  "heat.counting.perCategoryMax.*": { label: "Tricks that count" },
  "heat.counting.categoriesCounted": { label: "Number of categories that count", help: "Empty = every category." },
  "heat.counting.requireDistinctCategories": { label: "Counted tricks must come from different categories" },
  "heat.trickWeight": { label: "Multiplier on the counted tricks", help: "1 = no change." },
  "heat.countedWeights": { label: "Weights for the counted tricks, best first", help: "Comma separated, e.g. 1, 0.75, 0.5. Missing entries count as 1. Tie-breaks always use the raw scores." },
  "heat.countedWeights.*": { label: "Weight" },
  "heat.impression": { label: "Impression mark", off: "No impression mark", help: "One extra mark per rider for the whole heat (for example Variety or Overall)." },
  "heat.impression.label": { label: "Name shown to judges" },
  "heat.impression.help": { label: "Hint for judges" },
  "heat.impression.scale": { label: "Scale" },
  "heat.impression.scale.min": { label: "Lowest" },
  "heat.impression.scale.max": { label: "Highest" },
  "heat.impression.scale.step": { label: "Step" },
  "heat.impression.weight": { label: "Weight in the heat total" },
  "heat.impression.required": { label: "Publishing waits until every judge has marked every rider" },
  "heat.total": { label: "Heat total" },
  "heat.total.display": { label: "Show the total as", values: { raw: "Points", percent: "Percent", both: "Points and percent" } },
  "heat.total.maxRaw": { label: "Maximum possible total (for percent)", off: "Work it out automatically" },
  "heat.landedRatioHint": { label: "Show landed / attempted to judges before the impression mark" },
  "heat.maxAttemptsPerRider": { label: "Attempts allowed per rider per heat", off: "No limit" },
  "heat.duplicateWindowSec": { label: "Flag possible duplicate attempts within (seconds)", help: "Two spotters logging the same rider within this time." },

  categories: { label: "Trick categories", help: "Used by the spotter and by “best per category”." },
  "categories.*": { label: "Category" },
  "categories.*.key": { label: "Short code" },
  "categories.*.label": { label: "Name" },
  "categories.*.examples": { label: "Example tricks" },
  "categories.*.examples.*": { label: "Example" },
  "categories.*.colour": { label: "Colour (hex, optional)" },

  tieBreakers: { label: "Tie-breakers, in order", help: "The first one that separates two riders decides. Highest and next counted trick compare the raw scores." },
  "tieBreakers.*": {
    label: "Tie-breaker",
    values: {
      highest_counted_trick: "Highest counted trick",
      next_counted_trick: "Next counted trick",
      impression: "Impression mark",
      most_landed: "Most tricks landed",
      highest_any_trick: "Highest trick of any kind",
      head_judge: "Head judge decides",
      share_place: "Share the place",
    },
  },

  modifiers: { label: "Penalties and rider status" },
  "modifiers.interference": { label: "Interference" },
  "modifiers.interference.penalty": { label: "Penalty", values: { drop_best_trick: "Drop the best trick", percent: "Percent of the total", points: "Fixed points", none: "No penalty" } },
  "modifiers.interference.value": { label: "Amount", help: "Percent or points, depending on the penalty." },
  "modifiers.interference.allowMultiple": { label: "Each interference counts separately" },
  "modifiers.dns": { label: "Did not start (DNS)" },
  "modifiers.dns.placing": { label: "Placing", values: { last: "Last" } },
  "modifiers.dns.total": { label: "Total" },
  "modifiers.dnf": { label: "Did not finish (DNF)" },
  "modifiers.dnf.keepScores": { label: "Rider keeps the scores earned before stopping" },
  "modifiers.dsq": { label: "Disqualified (DSQ)" },
  "modifiers.dsq.placing": { label: "Placing", values: { last: "Last" } },
  "modifiers.dsq.total": { label: "Total" },

  heightSensor: { label: "Height sensor" },
  "heightSensor.enabled": { label: "Use a height sensor" },
  "heightSensor.source": { label: "Where heights come from", values: { manual: "Typed in by hand", woo_api: "WOO sensor feed" } },
  "heightSensor.use": { label: "How heights are used", values: { display: "Only shown", height_criterion: "Fills the Height criterion", bonus: "Adds bonus points" } },
  "heightSensor.mapping": { label: "Metres to score" },
  "heightSensor.mapping=linear": { label: "Straight line between two heights" },
  "heightSensor.mapping=bands": { label: "Height bands" },
  "heightSensor.mapping.fromM": { label: "From (metres)" },
  "heightSensor.mapping.toM": { label: "To (metres)" },
  "heightSensor.mapping.toScore": { label: "Score range" },
  "heightSensor.mapping.toScore.0": { label: "Score at the low height" },
  "heightSensor.mapping.toScore.1": { label: "Score at the high height" },
  "heightSensor.mapping.bands": { label: "Bands" },
  "heightSensor.mapping.bands.*": { label: "Band" },
  "heightSensor.mapping.bands.*.minM": { label: "From (metres)" },
  "heightSensor.mapping.bands.*.score": { label: "Score" },
  "heightSensor.bonus": { label: "Bonus points" },
  "heightSensor.bonus.perMetreAbove": { label: "Points per metre above the threshold" },
  "heightSensor.bonus.thresholdM": { label: "Threshold (metres)" },
  "heightSensor.bonus.capPoints": { label: "Most bonus points" },
  "heightSensor.award": { label: "Side award" },
  "heightSensor.award.highestJump": { label: "Rank riders by highest jump" },
};

/** Labels for the format template (docs/04 §2). */
export const FORMAT_HIDDEN = ["id", "basedOn", "kind"] as const;

const SEEDING_VALUES = { snake: "Snake (1 to A, 2 to B, …)", sequential: "In order", manual: "By hand", random: "Random draw" };
const UNEVEN_VALUES = { smaller_heats_for_top_seeds: "Smaller heats for the top seeds", one_larger_heat: "One larger heat", byes_top_seeds: "Byes for the top seeds" };
const RESEED_VALUES = { by_original_seed: "By original seed", by_heat_score: "By heat score", by_place_then_score: "By place, then score" };

export const FORMAT_LABELS: LabelMap = {
  name: { label: "Name" },
  description: { label: "Description" },
  entrants: { label: "Field size this format suits" },
  "entrants.min": { label: "Fewest riders" },
  "entrants.max": { label: "Most riders", off: "No upper limit" },
  vestColours: { label: "Vest colours, in slot order" },
  "vestColours.*": { label: "Colour" },
  timing: { label: "Default timing (minutes)" },
  "timing.defaultHeatMin": { label: "Heat length" },
  "timing.defaultBreakAfterHeatMin": { label: "Break after each heat" },
  "timing.defaultBreakAfterRoundMin": { label: "Break after each round" },

  rounds: { label: "Rounds", help: "Each round is dealt into heats. Later rounds take riders from earlier rounds." },
  "rounds.*": { label: "Round" },
  "rounds.*.id": { label: "Short code", help: "Used by other rounds to refer to this one, e.g. R1, SF, F." },
  "rounds.*.name": { label: "Name" },
  "rounds.*.shortName": { label: "Short name" },
  "rounds.*.heatSize": { label: "Riders per heat" },
  "rounds.*.durationMin": { label: "Heat length (minutes)", help: "Empty = the default timing above." },
  "rounds.*.breakAfterHeatMin": { label: "Break after each heat (minutes)" },
  "rounds.*.breakAfterRoundMin": { label: "Break after the round (minutes)" },
  "rounds.*.entrantsFrom": { label: "Where the riders come from" },
  "rounds.*.entrantsFrom.*": { label: "Source" },
  "rounds.*.entrantsFrom.*=seeds": { label: "The seed list (all riders)" },
  "rounds.*.entrantsFrom.*=round_places": { label: "Places from an earlier round" },
  "rounds.*.entrantsFrom.*.round": { label: "Earlier round" },
  "rounds.*.entrantsFrom.*.places": { label: "Places that come through", help: "Comma separated, e.g. 1, 2." },
  "rounds.*.entrantsFrom.*.places.*": { label: "Place" },
  "rounds.*.advance.*.places.*": { label: "Place" },
  "rounds.*.seeding": { label: "How riders are dealt into heats", values: SEEDING_VALUES },
  "rounds.*.uneven": { label: "When the field does not divide evenly", values: UNEVEN_VALUES },
  "rounds.*.heatCountOverride": { label: "Force this number of heats" },
  "rounds.*.reseed": { label: "Order riders for the next round", values: RESEED_VALUES },
  "rounds.*.advance": { label: "Where each place goes" },
  "rounds.*.advance.*": { label: "Rule" },
  "rounds.*.advance.*.places": { label: "Places", off: "Everyone else", help: "Comma separated, e.g. 1, 2." },
  "rounds.*.advance.*.to": { label: "Goes to", help: "A round, “eliminated” or “final_placing”." },
  "rounds.*.crossHeat": { label: "Rank riders across all heats (pools)", off: "Not used" },
  "rounds.*.crossHeat.advanceTop": { label: "How many advance" },
  "rounds.*.crossHeat.to": { label: "Advance to round" },
  "rounds.*.crossHeat.combine": { label: "Combine heat scores by", values: { best: "Best heat", sum: "Sum of heats" } },
  "rounds.*.crossHeat.tieBreak": { label: "Tie-break", values: { scoring_model_then_seed: "Scoring rules, then seed" } },
  "rounds.*.minRidersToRun": { label: "Fewest riders for a heat to run" },

  generator: { label: "Format generator" },
  "generator=single_elimination": { label: "Single elimination (heats of N, top riders advance)" },
  "generator=dingle_elimination": { label: "Dingle elimination (repechage)" },
  "generator=pools_to_final": { label: "Pools then a final" },
  "generator.params": { label: "Settings" },
  "generator.params.heatSize": { label: "Riders per heat" },
  "generator.params.advancePerHeat": { label: "Riders advancing from each heat" },
  "generator.params.finalSize": { label: "Riders in the final" },
  "generator.params.earlyMin": { label: "Early rounds: heat length (minutes)" },
  "generator.params.semiMin": { label: "Semi-finals: heat length (minutes)" },
  "generator.params.finalMin": { label: "Final: heat length (minutes)" },
  "generator.params.seeding": { label: "How riders are dealt into heats", values: SEEDING_VALUES },
  "generator.params.uneven": { label: "When the field does not divide evenly", values: UNEVEN_VALUES },
  "generator.params.reseed": { label: "Order riders for the next round", values: RESEED_VALUES },
  "generator.params.r1HeatSize": { label: "Round 1: riders per heat" },
  "generator.params.r1Min": { label: "Round 1: heat length (minutes)" },
  "generator.params.repMin": { label: "Repechage: heat length (minutes)" },
  "generator.params.koMin": { label: "Knock-out: heat length (minutes)" },
  "generator.params.finalists": { label: "Riders in the final" },
  "generator.params.poolMin": { label: "Pool heat length (minutes)" },
  "generator.params.poolRounds": { label: "Pool rounds", values: { "1": "One", "2": "Two" } },
  "generator.params.poolCombine": { label: "Combine pool rounds by", values: { best: "Best heat", sum: "Sum of heats" } },
  "generator.params.crossPoolTieBreak": { label: "Tie-break between pools", values: { scoring_model_then_seed: "Scoring rules, then seed" } },

  placings: { label: "Final placings" },
  "placings.eliminated": { label: "Riders knocked out share their place", values: { shared: "Shared (e.g. 13=)", by_heat_score: "Ranked by heat score" } },
  "placings.finalHeatIsRanking": { label: "The final heat decides places 1 to N" },
  flagOut: { label: "Flag-out (lowest rider leaves mid-heat)", off: "No flag-out" },
  "flagOut.rounds": { label: "Rounds with flag-out" },
  "flagOut.rounds.*": { label: "Round code" },
  "flagOut.atMin": { label: "At minute" },
  "flagOut.count": { label: "Riders flagged out" },
};
