/**
 * Every word of the organiser preview (/design/organiser) and of the new organiser components. House words: Rider label, Lycra, score, Impression / Variety score.
 * It lives in its own file for now so the preview touches no existing file; Phase 7a-1 moves these groups into `src/lib/ui-copy.ts` (docs/PLAN-phase-7a.md step 7).
 * `copy.test.ts` keeps the banned words out of it.
 */
export const orgCopy = {
  states: {
    done: { label: "Done" },
    attention: { label: "Needs attention" },
    not_started: { label: "Not started" },
    live: { label: "Live" },
    held: { label: "On hold" },
    draft: { label: "Draft" },
    published: { label: "Published" },
  },
  rider: { confirmed: "Confirmed", waiting: "Waiting list", withdrawn: "Withdrawn" },

  page: {
    title: "Organiser design preview",
    notLive: "Design preview — nothing here is live",
    intro: "This is how the organiser screens will look and feel, built from the real new parts with made-up data. Open it on your laptop and on your phone, try the buttons, then reply “approved” or list what to change. Nothing else in Phase 7a starts before that.",
    note: "Colours, text size and the frame are saved on this device only. Nothing here is saved anywhere else.",
    menu: "Menu",
    menuLabel: "Sections of this page",
    backToTop: "Back to the top",
    theme: "Screen colours",
    day: "Daylight",
    dark: "Dark",
    textSize: "Text size",
    normal: "Normal",
    large: "Large",
    frame: "Show as",
    laptop: "Laptop",
    phone: "Phone",
    frameLaptop: "Laptop, 1440 px wide",
    framePhone: "Phone, 390 px wide",
    sizesNote: "Controls and rows are 40 px high on a computer and 44 px on a touch screen (48 px with Large text). The official judge and spotter screens keep their own sizes.",
    sections: {
      shell: "Event shell: top bar and the seven steps",
      dashboard: "Go live: the dashboard",
      riders: "Riders: a dense table",
      "settings-simple": "Divisions settings: Simple",
      "settings-advanced": "Divisions settings: Advanced open",
      footer: "Previous and Next at the foot of a step",
      numbers: "Number boxes",
      buttons: "Buttons, disabled buttons and status pills",
      phone: "One organiser page on a phone",
    } as Record<string, string>,
    notes: {
      shell: "The top bar holds the event name, dates, state, the public link with its QR code and the organisation switcher. The rail lists the seven steps, each with its state and one line of reason. The Riders step is open.",
      dashboard: "The start of event day: what is still missing, the heat that is running and the next ones, the wind call, quick actions and the links to share. Try Hold and Resume.",
      riders: "Dense rows, a header that stays put, search, filters, tick boxes with a bar for the ticked riders, a name you can edit in place, and what an empty list says. Type “ma” in the search box.",
      "settings-simple": "Six plain dials, each with a line under it and a “?” with an example. The sentence at the top is made by the real scoring code and changes as you change a dial. “Load…” is a small button in the corner.",
      "settings-advanced": "The same panel with “More settings” open. The Simple dials stay on top and the sentence stays in view while you scroll.",
      footer: "Next saves what you typed first. On the last step there is only Previous. On a phone the bar sticks to the bottom of the screen.",
      numbers: "Each box is as wide as the biggest number it accepts, with the digits at the right. Compare with today’s full-width box. The centred version is the earlier idea; tell me which you prefer.",
      buttons: "One main button per screen, then the quiet ones. A button that cannot be used says why, in words under it. Every state is an icon and a word, never colour alone.",
      phone: "The Riders step on a phone: the steps become a drop-down that shows each state, the table keeps its header, and Previous and Next stay at the bottom.",
    } as Record<string, string>,
  },

  shell: {
    railLabel: "Event steps",
    stepPickerLabel: "Step",
    stepOption: (n: number, label: string, state: string) => `${n}. ${label} — ${state}`,
    organisation: "Organisation",
    publicLink: "Public link",
    qrAlt: (url: string) => `QR code for ${url}`,
    copyLink: "Copy link",
    copied: "Copied",
    openLink: "Open",
    account: "Account",
    preferences: "On this device",
    note: "Note",
    password: "Set or change password",
    signOut: "Sign out",
  },

  footer: {
    previous: (label: string) => `Previous: ${label}`,
    next: (label: string) => `Next: ${label}`,
  },

  table: {
    all: "All",
    showing: (shown: number, total: number) => (shown === total ? `${total} shown` : `${shown} of ${total} shown`),
    selected: (n: number) => `${n} selected`,
    selectedHidden: (n: number, hidden: number) => `${n} selected, ${hidden} hidden by the filter`,
    bulkLabel: "Actions for the ticked rows",
    clear: "Clear",
    selectAll: "Select all shown",
    selectRow: (name: string) => `Select ${name}`,
    noMatch: (q: string) => (q.trim() ? `No rider matches “${q.trim()}”.` : "Nothing matches the filter."),
    saved: "Saved",
  },

  riders: {
    caption: "Riders of Preview Cup",
    search: "Search riders",
    divisionFilter: "Division",
    statusFilter: "Status",
    colBib: "Bib",
    colName: "Name",
    colCountry: "Country",
    colDivision: "Division",
    colKite: "Kite (m)",
    colStatus: "Status",
    editName: (name: string) => `Edit name of ${name}`,
    editKite: (name: string) => `Edit kite size of ${name}`,
    setStatus: "Set status",
    moveTo: "Move to division",
    delete: "Delete",
    deleteQuestion: (n: number) => `Delete ${n} ${n === 1 ? "rider" : "riders"}?`,
    deleteYes: (n: number) => `Delete ${n}`,
    cancel: "Cancel",
    title: "Riders",
    stepIntro: "Riders taken from the registration list. Click a name or a kite size to change it.",
    emptyTitle: "No riders in Juniors yet",
    emptyBody: "Add one below, paste a list, or open registrations.",
    addRider: "Add a rider",
    pasteList: "Paste a list",
    openRegistrations: "Open registrations",
    emptyLabel: "What an empty division says",
    import: "Import",
    print: "Print",
  },

  settings: {
    helpLabel: (label: string) => `About “${label}”`,
    example: (text: string) => `Example: ${text}`,
    load: "Load…",
    builtIn: "Built-in",
    mine: "My organisation’s",
    saveAsPreset: "Save as preset…",
    sentenceLabel: "In words",
    more: (n: number) => `More settings (${n})`,
    panelTitle: "Pro Men · Scoring",
    on: "On",
    off: "Off",
    builtInNames: ["Best 3 of 7 attempts + Variety", "Best 3 tricks + Impression", "Single best trick"],
    mineNames: ["Arrow launch, Pro Men", "Club quick format"],
    dials: {
      bestN: { label: "Tricks that count", explanation: "How many of a rider’s best tricks are added up.", example: "With 3, a rider who landed 5 tricks is scored on the 3 highest.", unit: "best" },
      attempts: { label: "Attempts per rider", explanation: "The most attempts a rider can have in one heat.", example: "With 7, the spotter cannot log an 8th attempt.", unit: "attempts" },
      judges: { label: "Judges on the panel", explanation: "How many judges score each trick.", example: "With 3 judges, every trick gets 3 scores that are combined into one.", unit: "judges" },
      aggregate: { label: "How the judges’ scores combine", explanation: "Average everyone, or drop the highest and lowest first.", example: "With 5 judges and “Drop highest and lowest”, the middle 3 scores are averaged." },
      impression: { label: "Impression / Variety score", explanation: "One extra score per rider for the whole heat.", example: "After the heat each judge gives each rider one score, for example 7.5 out of 10." },
      impressionMax: { label: "Highest Impression score", explanation: "The top of the scale a judge can use.", example: "With 10, the scale runs from 0 to 10.", unit: "points" },
    },
    aggregateOptions: { mean: "Average of all judges", trimmed_mean: "Drop highest and lowest, average the rest", median: "Middle score" },
    advanced: {
      trickWeight: { label: "Trick score multiplier", explanation: "Multiplies every trick score before it is added up.", example: "With 1.5, a trick scored 6.0 counts as 9.0.", unit: "×" },
      impressionWeight: { label: "Impression multiplier", explanation: "Multiplies the Impression score before it is added.", example: "With 2, an Impression score of 7.0 adds 14.0.", unit: "×" },
      duplicateWindow: { label: "Duplicate attempt window", explanation: "Attempts logged this close together are flagged as a possible double entry.", example: "With 20, two attempts logged 15 seconds apart are flagged.", unit: "seconds" },
      outlier: { label: "Warn when a judge differs by", explanation: "A score this far from the others is highlighted for the head judge.", example: "With 20, a 5.0 next to two 8.0s is highlighted.", unit: "%" },
      trimMin: { label: "Drop highest and lowest from", explanation: "The smallest panel where the highest and lowest scores are dropped.", example: "With 5, a panel of 3 is still averaged plainly.", unit: "judges" },
      maxJudges: { label: "Most judges on a panel", explanation: "The largest panel a heat may have.", example: "With 6, a seventh judge cannot be added to the panel.", unit: "judges" },
      decimals: { label: "Decimals shown", explanation: "How many digits after the point scores are shown with.", example: "With 1, a score of 7.25 is shown as 7.3.", unit: "digits" },
      distinct: { label: "A trick counts once", explanation: "Repeating a trick by name does not add to the total.", example: "A second Backroll in the same heat is scored but not counted." },
      requireAll: { label: "Wait for every judge", explanation: "A trick is complete only when every judge has scored it.", example: "With 3 judges, a trick with 2 scores stays open." },
      ratio: { label: "Show the landed ratio", explanation: "Shows landed attempts out of all attempts next to each rider.", example: "A rider with 5 landed of 7 attempts shows 5 / 7." },
    },
  },

  dashboard: {
    readinessTitle: "Ready to run?",
    ready: "Ready to run",
    thingsLeft: (n: number) => `${n} ${n === 1 ? "thing" : "things"} left`,
    fix: "Fix",
    fixLabel: (what: string) => `Fix: ${what}`,
    nowTitle: "Now and next",
    serverTime: (t: string) => `Server time ${t}, Cairo`,
    left: "left",
    next: "Next",
    after: "After that",
    est: (t: string) => `est. ${t}`,
    windTitle: "Wind call",
    windBody: "The organiser or the head judge sets the wind call here.",
    windButton: "Set wind call",
    windWaiting: "The wind call arrives with the public pages.",
    actionsTitle: "Quick actions",
    hold: "Hold",
    resume: "Resume at…",
    alreadyHeld: "The run order is already on hold.",
    notHeld: "Nothing is on hold.",
    shift: (min: number) => `Shift +${min} min`,
    headConsole: "Open head judge console",
    bigScreen: "Big screen",
    bigScreenWaiting: "The big screen comes with the public pages.",
    reset: "Reset event…",
    resetRefused: (heat: string) => `${heat} is running. End it first.`,
    printCards: "Print official cards",
    timetableTitle: "Today’s timetable",
    colStart: "Start",
    colHeat: "Heat",
    colEnd: "End",
    colLength: "Min",
    joinTitle: "Officials’ join link",
    joinNote: "Judges, spotters and the head judge open this on their phones and enter their PIN.",
    publicTitle: "Public event page",
    publicNote: "Riders and spectators follow the event here once you publish it.",
  },

  buttons: {
    primary: "Primary",
    secondary: "Secondary",
    quiet: "Quiet",
    danger: "Danger",
    enabled: "Enabled",
    disabled: "Disabled, with its reason",
    reasons: {
      primary: "Fill in the event name first.",
      secondary: "Lock the draw first.",
      quiet: "Nobody is ticked.",
      danger: "Heat 2 is running. End it first.",
    },
    states: "Status pills",
    pillsNote: "An icon and a word, in every state.",
  },

  numbers: {
    today: "Today: the box fills its container",
    right: "New: as wide as its biggest number, digits at the right",
    centre: "Earlier idea: digits centred",
    one: "Riders per heat",
    two: "Heat length",
    three: "Most riders",
    decimal: "Impression scale step",
    units: { riders: "riders", min: "min", points: "points" },
  },

  footerDemo: {
    step2: "Divisions, step 2 of 7",
    step6: "Run order, step 6 of 7",
    step7: "Go live, step 7 of 7: only Previous",
    labels: { event: "Event", divisions: "Divisions", riders: "Riders", officials: "Officials", draw: "Draw", schedule: "Run order" },
  },

  phoneNote: "On a phone the footer is part of the screen: it stays at the bottom while the list scrolls.",
} as const;
